// examples/svelte_invaders/src/components/HUD.svelte
<script lang="ts">
	import { Box, Text, Spacer, Badge } from '@wolfie/svelte'
	import { BRAND } from '../theme'

	//#region Props
	let { score, lives, wave, showFps, fps }: {
		score: number
		lives: number
		wave: number
		showFps?: boolean
		fps?: number
	} = $props()
	//#endregion Props

	let formattedScore = $derived(score.toString().padStart(6, '0'))
	let livesHearts = $derived(
		Array.from({ length: lives }, () => '♥').join(' ')
	)
</script>

<Box style={{ flexDirection: 'row', width: '100%' }}>
	<Box>
		<Text style={{ color: BRAND.primary }} className="font-bold">
			SCORE{' '}
		</Text>
		<Text
			style={{ color: BRAND.bgDark, backgroundColor: BRAND.primary }}
			className="font-bold"
		>
			{' ' + formattedScore + ' '}
		</Text>
	</Box>

	<Spacer />

	<Box>
		<Text style={{ color: BRAND.error }} className="font-bold">
			LIVES{' '}
		</Text>
		<Text style={{ color: BRAND.error }}>{livesHearts}</Text>
	</Box>

	<Spacer />

	<Box>
		<Text style={{ color: BRAND.primary }} className="font-bold">
			WAVE{' '}
		</Text>
		<Badge color={BRAND.primaryDark} label={wave.toString()} />
	</Box>

	{#if showFps}
		<Spacer />
		<Box>
			<Text style={{ color: BRAND.textMuted }}>FPS </Text>
			<Text style={{ color: BRAND.success }}>{fps ?? 0}</Text>
		</Box>
	{/if}
</Box>

// examples/vue_invaders/src/components/HUD.vue
<script setup lang="ts">
import { computed } from 'vue'
import { Box, Text, Spacer } from '@wolf-tui/vue'
import { BRAND } from '../theme'

//#region Props
const props = defineProps<{
	score: number
	lives: number
	wave: number
	showFps?: boolean
	fps?: number
}>()
//#endregion Props

//#region Computed
const formattedScore = computed(() => props.score.toString().padStart(6, '0'))
const livesHearts = computed(() =>
	Array.from({ length: props.lives }, () => '♥').join(' ')
)
//#endregion Computed
</script>

<template>
	<Box :style="{ flexDirection: 'row', width: '100%' }">
		<Box>
			<Text :style="{ color: BRAND.primary }" class="font-bold">SCORE </Text>
			<Text
				:style="{ color: BRAND.bgDark, backgroundColor: BRAND.primary }"
				class="font-bold"
			>
				{{ ' ' + formattedScore + ' ' }}
			</Text>
		</Box>

		<Spacer />

		<Box>
			<Text :style="{ color: BRAND.error }" class="font-bold">LIVES </Text>
			<Text :style="{ color: BRAND.error }">{{ livesHearts }}</Text>
		</Box>

		<Spacer />

		<Box>
			<Text :style="{ color: BRAND.primary }" class="font-bold">WAVE </Text>
			<Text
				:style="{ color: BRAND.bgDark, backgroundColor: BRAND.primaryDark }"
				class="font-bold"
			>
				{{ ' ' + wave + ' ' }}
			</Text>
		</Box>

		<template v-if="showFps">
			<Spacer />
			<Box>
				<Text :style="{ color: BRAND.textMuted }">FPS </Text>
				<Text :style="{ color: BRAND.success }">{{ fps ?? 0 }}</Text>
			</Box>
		</template>
	</Box>
</template>
