// examples/react_invaders/src/components/HUD.tsx
import { Box, Text, Spacer } from '@wolfie/react'
import { BRAND } from '../theme'

//#region Types
type HUDProps = {
	score: number
	lives: number
	wave: number
	showFps?: boolean
	fps?: number
}
//#endregion Types

//#region Component
export function HUD({
	score,
	lives,
	wave,
	showFps = false,
	fps = 0,
}: HUDProps) {
	return (
		<Box style={{ flexDirection: 'row', width: '100%' }}>
			<Box>
				<Text style={{ color: BRAND.primary }} className="font-bold">
					SCORE{' '}
				</Text>
				<Text
					style={{ color: BRAND.bgDark, backgroundColor: BRAND.primary }}
					className="font-bold"
				>
					{' '}
					{score.toString().padStart(6, '0')}{' '}
				</Text>
			</Box>

			<Spacer />

			<Box>
				<Text style={{ color: BRAND.error }} className="font-bold">
					LIVES{' '}
				</Text>
				<Text style={{ color: BRAND.error }}>
					{Array.from({ length: lives }, () => '♥').join(' ')}
				</Text>
			</Box>

			<Spacer />

			<Box>
				<Text style={{ color: BRAND.primary }} className="font-bold">
					WAVE{' '}
				</Text>
				<Text
					style={{ color: BRAND.bgDark, backgroundColor: BRAND.primaryDark }}
					className="font-bold"
				>
					{' '}
					{wave}{' '}
				</Text>
			</Box>

			{showFps && (
				<>
					<Spacer />
					<Box>
						<Text style={{ color: BRAND.textMuted }}>FPS </Text>
						<Text style={{ color: BRAND.success }}>{fps}</Text>
					</Box>
				</>
			)}
		</Box>
	)
}
//#endregion Component

// apps/solid-invaders/src/components/HUD.tsx
import { createMemo } from 'solid-js'
import { Box, Text, Spacer, Show } from '@wolfie/solid'
import { BRAND } from '../theme'

//#region Props
type HUDProps = {
	score: number
	lives: number
	wave: number
	showFps?: boolean
	fps?: number
}
//#endregion Props

//#region Component
export default function HUD(props: HUDProps) {
	const formattedScore = createMemo(() =>
		props.score.toString().padStart(6, '0')
	)
	const livesHearts = createMemo(() =>
		Array.from({ length: props.lives }, () => '♥').join(' ')
	)

	return (
		<Box style={{ flexDirection: 'row', width: '100%' }}>
			<Box>
				<Text style={{ color: BRAND.primary }} className="font-bold">
					SCORE{' '}
				</Text>
				<Text
					style={{ color: BRAND.bgDark, backgroundColor: BRAND.primary }}
					className="font-bold"
				>
					{' ' + formattedScore() + ' '}
				</Text>
			</Box>

			<Spacer />

			<Box>
				<Text style={{ color: BRAND.error }} className="font-bold">
					LIVES{' '}
				</Text>
				<Text style={{ color: BRAND.error }}>{livesHearts()}</Text>
			</Box>

			<Spacer />

			<Box>
				<Text style={{ color: BRAND.primary }} className="font-bold">
					WAVE{' '}
				</Text>
				<Text
					style={{ color: BRAND.bgDark, backgroundColor: BRAND.primaryDark }}
					className="font-bold"
				>
					{' ' + props.wave + ' '}
				</Text>
			</Box>

			<Show when={props.showFps}>
				<Spacer />
				<Box>
					<Text style={{ color: BRAND.textMuted }}>FPS </Text>
					<Text style={{ color: BRAND.success }}>{props.fps ?? 0}</Text>
				</Box>
			</Show>
		</Box>
	)
}
//#endregion Component
