// packages/svelte/src/components/OrderedListItem.svelte
<script lang="ts">
	import { getContext, type Snippet } from 'svelte'
	import Box from './Box.svelte'
	import Text from './Text.svelte'
	import { OL_COUNTER_CTX } from '../context/symbols.js'
	import { useComponentTheme } from '../theme/index.js'
	import { orderedListTheme, type OrderedListTheme } from './list-theme.js'

	let { children }: {
		children: Snippet
	} = $props()

	const ctx = getContext<{ getNextIndex: () => number } | undefined>(OL_COUNTER_CTX)
	const index = ctx?.getNextIndex() ?? 1

	const theme = useComponentTheme<OrderedListTheme>('OrderedList')
	const { styles } = theme ?? orderedListTheme
</script>

<Box {...styles.listItem()}>
	<Text {...styles.marker()}>{index}.</Text>
	<Box {...styles.content()}>
		{@render children()}
	</Box>
</Box>

// packages/react/src/components/ui/OrderedList/OrderedListItem.tsx
import {useContext, type ReactNode} from 'react';
import Box from '../../Box.js';
import Text from '../../Text.js';
import {useComponentTheme} from '../../../theme/theme.js';
import {OrderedListItemContext} from './OrderedListItemContext.js';
import type {OrderedListTheme} from './theme.js';

export type OrderedListItemProps = {
	/**
	 * List item content.
	 */
	readonly children: ReactNode;
};

export function OrderedListItem({children}: OrderedListItemProps) {
	const {marker} = useContext(OrderedListItemContext);
	const {styles} = useComponentTheme<OrderedListTheme>('OrderedList');

	return (
		<Box {...styles.listItem()}>
			<Text {...styles.marker()}>{marker}</Text>
			<Box {...styles.content()}>{children}</Box>
		</Box>
	);
}
