// packages/svelte/src/components/UnorderedListItem.svelte
<script lang="ts">
	import { getContext, type Snippet } from 'svelte'
	import figures from 'figures'
	import Box from './Box.svelte'
	import Text from './Text.svelte'
	import { UL_MARKER_CTX } from '../context/symbols.js'
	import { useComponentTheme } from '../theme/index.js'
	import { unorderedListTheme, type UnorderedListTheme } from './list-theme.js'

	let { children }: {
		children: Snippet
	} = $props()

	const marker = getContext<string | undefined>(UL_MARKER_CTX) ?? figures.line

	const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
	const { styles } = theme ?? unorderedListTheme
</script>

<Box {...styles.listItem()}>
	<Text {...styles.marker()}>{marker}</Text>
	<Box {...styles.content()}>
		{@render children()}
	</Box>
</Box>

// packages/react/src/components/ui/UnorderedList/UnorderedListItem.tsx
import { useContext, type ReactNode } from 'react'
import Box from '../../Box'
import Text from '../../Text'
import { useComponentTheme } from '../../../theme/theme'
import { UnorderedListItemContext } from './UnorderedListItemContext'
import type { UnorderedListTheme } from './theme'

export type UnorderedListItemProps = {
	/**
	 * List item content.
	 */
	readonly children: ReactNode
}

export function UnorderedListItem({ children }: UnorderedListItemProps) {
	const { marker } = useContext(UnorderedListItemContext)
	const { styles } = useComponentTheme<UnorderedListTheme>('UnorderedList')

	return (
		<Box {...styles.listItem()}>
			<Text {...styles.marker()}>{marker}</Text>
			<Box {...styles.content()}>{children}</Box>
		</Box>
	)
}
