// packages/svelte/src/components/UnorderedList.svelte
<script lang="ts">
	import { setContext, getContext, type Snippet } from 'svelte'
	import figures from 'figures'
	import Box from './Box.svelte'
	import { UL_DEPTH_CTX, UL_MARKER_CTX } from '../context/symbols.js'
	import { useComponentTheme } from '../theme/index.js'
	import { unorderedListTheme, type UnorderedListTheme } from './list-theme.js'

	let { children }: {
		children: Snippet
	} = $props()

	const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
	const { styles, config } = theme ?? unorderedListTheme

	const markers = config().marker
	const markerList = Array.isArray(markers) ? markers : [markers]

	const parentDepth = getContext<number | undefined>(UL_DEPTH_CTX) ?? 0
	const marker = markerList[parentDepth % markerList.length] ?? figures.bullet

	setContext(UL_DEPTH_CTX, parentDepth + 1)
	setContext(UL_MARKER_CTX, marker)
</script>

<Box {...styles.list()}>
	{@render children()}
</Box>

// packages/react/src/components/ui/UnorderedList/UnorderedList.tsx
import { useMemo, type ReactNode, useContext } from 'react'
import Box from '../../Box'
import { useComponentTheme } from '../../../theme/theme'
import { UnorderedListItem } from './UnorderedListItem'
import { UnorderedListContext } from './UnorderedListContext'
import { UnorderedListItemContext } from './UnorderedListItemContext'
import type { UnorderedListTheme } from './theme'
import { defaultMarker } from './constants'

export type UnorderedListProps = {
	/**
	 * List items.
	 */
	readonly children: ReactNode
}

function UnorderedListComponent({ children }: UnorderedListProps) {
	const { depth } = useContext(UnorderedListContext)
	const { styles, config } =
		useComponentTheme<UnorderedListTheme>('UnorderedList')

	const listContext = useMemo(
		() => ({
			depth: depth + 1,
		}),
		[depth]
	)

	const listItemContext = useMemo(() => {
		const { marker } = config()

		if (typeof marker === 'string') {
			return { marker }
		}

		if (Array.isArray(marker)) {
			return {
				marker: marker[depth] ?? marker.at(-1) ?? defaultMarker,
			}
		}

		return {
			marker: defaultMarker,
		}
	}, [config, depth])

	return (
		<UnorderedListContext.Provider value={listContext}>
			<UnorderedListItemContext.Provider value={listItemContext}>
				<Box {...styles.list()}>{children}</Box>
			</UnorderedListItemContext.Provider>
		</UnorderedListContext.Provider>
	)
}

export const UnorderedList = Object.assign(UnorderedListComponent, {
	Item: UnorderedListItem,
})
