// packages/vue/src/components/UnorderedList.tsx
import {
	defineComponent,
	inject,
	provide,
	type PropType,
	type VNode,
} from 'vue'
import figures from 'figures'
import { Box, type BoxProps } from './Box'
import { Text, type TextProps } from './Text'
import { useComponentTheme, type IComponentTheme } from '../theme'
import {
	UnorderedListSymbol,
	UnorderedListItemSymbol,
} from '../context/symbols'

//#region Types
export type UnorderedListContextProps = {
	/**
	 * Depth of the list.
	 */
	depth: number
}

export type UnorderedListItemContextProps = {
	/**
	 * Marker that's displayed before each list item.
	 */
	marker: string
}

export type UnorderedListTheme = {
	styles: {
		list: () => Partial<BoxProps>
		listItem: () => Partial<BoxProps>
		marker: () => Partial<TextProps>
		content: () => Partial<BoxProps>
	}
	config: () => {
		marker: string | string[]
	}
}

export interface UnorderedListProps {
	/**
	 * List items.
	 */
	children?: VNode[]
}

export interface UnorderedListItemProps {
	/**
	 * List item content.
	 */
	children?: VNode[]
}
//#endregion Types

//#region Constants
const defaultMarker = figures.line
const defaultMarkers = [figures.bullet, figures.line, figures.pointer]
//#endregion Constants

//#region Theme
export const unorderedListTheme = {
	styles: {
		list: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'column',
			},
		}),
		listItem: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'row',
			},
		}),
		marker: (): Partial<TextProps> => ({
			style: {
				color: 'green',
			},
		}),
		content: (): Partial<BoxProps> => ({
			style: {
				flexDirection: 'column',
				marginLeft: 1,
			},
		}),
	},
	config() {
		return {
			marker: defaultMarkers,
		}
	},
} satisfies IComponentTheme
//#endregion Theme

//#region UnorderedListItem Component
export const UnorderedListItem = defineComponent({
	name: 'UnorderedListItem',
	props: {
		children: {
			type: Array as PropType<VNode[]>,
			default: undefined,
		},
	},
	setup(props, { slots }) {
		const itemContext = inject<UnorderedListItemContextProps>(
			UnorderedListItemSymbol,
			{ marker: defaultMarker }
		)

		return () => {
			const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
			const styles = theme?.styles ?? unorderedListTheme.styles

			const children = slots.default?.() ?? props.children

			return (
				<Box {...styles.listItem()}>
					<Text {...styles.marker()}>{itemContext.marker}</Text>
					<Box {...styles.content()}>{children}</Box>
				</Box>
			)
		}
	},
})
//#endregion UnorderedListItem Component

//#region UnorderedList Component
const UnorderedListComponent = defineComponent({
	name: 'UnorderedList',
	props: {
		children: {
			type: Array as PropType<VNode[]>,
			default: undefined,
		},
	},
	setup(props, { slots }) {
		const parentContext = inject<UnorderedListContextProps>(
			UnorderedListSymbol,
			{ depth: 0 }
		)

		// Compute contexts and provide them in setup
		const theme = useComponentTheme<UnorderedListTheme>('UnorderedList')
		const config = theme?.config ?? unorderedListTheme.config

		// Determine marker based on depth
		const { marker: markerConfig } = config()
		let marker: string

		if (typeof markerConfig === 'string') {
			marker = markerConfig
		} else if (Array.isArray(markerConfig)) {
			marker =
				markerConfig[parentContext.depth] ??
				markerConfig.at(-1) ??
				defaultMarker
		} else {
			marker = defaultMarker
		}

		// Provide contexts for nested lists and items
		const listContext: UnorderedListContextProps = {
			depth: parentContext.depth + 1,
		}
		const itemContext: UnorderedListItemContextProps = { marker }

		provide<UnorderedListContextProps>(UnorderedListSymbol, listContext)
		provide<UnorderedListItemContextProps>(UnorderedListItemSymbol, itemContext)

		return () => {
			const styles = theme?.styles ?? unorderedListTheme.styles
			const children = slots.default?.() ?? props.children ?? []

			return <Box {...styles.list()}>{children}</Box>
		}
	},
})

export const UnorderedList = Object.assign(UnorderedListComponent, {
	Item: UnorderedListItem,
})
//#endregion UnorderedList Component

export type { UnorderedListProps as Props, UnorderedListProps as IProps }

// packages/react/src/components/ui/UnorderedList/UnorderedList.tsx
import { useMemo, type ReactNode, useContext } from 'react'
import Box from '../../Box'
import { useComponentTheme } from '../../../theme/theme'
import { UnorderedListItem } from './UnorderedListItem'
import { UnorderedListContext } from './UnorderedListContext'
import { UnorderedListItemContext } from './UnorderedListItemContext'
import type { UnorderedListTheme } from './theme'
import { defaultMarker } from './constants'

export type UnorderedListProps = {
	/**
	 * List items.
	 */
	readonly children: ReactNode
}

function UnorderedListComponent({ children }: UnorderedListProps) {
	const { depth } = useContext(UnorderedListContext)
	const { styles, config } =
		useComponentTheme<UnorderedListTheme>('UnorderedList')

	const listContext = useMemo(
		() => ({
			depth: depth + 1,
		}),
		[depth]
	)

	const listItemContext = useMemo(() => {
		const { marker } = config()

		if (typeof marker === 'string') {
			return { marker }
		}

		if (Array.isArray(marker)) {
			return {
				marker: marker[depth] ?? marker.at(-1) ?? defaultMarker,
			}
		}

		return {
			marker: defaultMarker,
		}
	}, [config, depth])

	return (
		<UnorderedListContext.Provider value={listContext}>
			<UnorderedListItemContext.Provider value={listItemContext}>
				<Box {...styles.list()}>{children}</Box>
			</UnorderedListItemContext.Provider>
		</UnorderedListContext.Provider>
	)
}

export const UnorderedList = Object.assign(UnorderedListComponent, {
	Item: UnorderedListItem,
})
