// packages/react/src/components/Alert/Alert.tsx
import { Box } from '../Box'
import { Text } from '../Text'
import { useComponentTheme } from '../../theme/theme'
import { type IAlertProps, type IAlertTheme } from './types'

//#region Component
export function Alert({ children, variant, title }: IAlertProps) {
	const { styles, config } = useComponentTheme<IAlertTheme>('Alert')

	return (
		<Box {...styles.container({ variant })}>
			<Box {...styles.iconContainer()}>
				<Text {...styles.icon({ variant })}>{config({ variant }).icon}</Text>
			</Box>

			<Box {...styles.content()}>
				{title && <Text {...styles.title()}>{title}</Text>}
				<Text {...styles.message()}>{children}</Text>
			</Box>
		</Box>
	)
}
//#endregion Component

// packages/svelte/src/components/Alert.svelte
<script lang="ts">
	import {
		renderAlert,
		defaultAlertTheme,
		type AlertRenderTheme,
	} from '@wolfie/shared'
	import { mountWNode } from '../wnode/wnode-to-svelte.js'
	import { useComponentTheme } from '../theme/index.js'

	//#region Types
	type AlertVariant = 'info' | 'success' | 'error' | 'warning'
	//#endregion Types

	let { variant, title, message = '' }: {
		variant: AlertVariant
		title?: string
		message?: string
	} = $props()

	const theme = useComponentTheme<AlertRenderTheme>('Alert')
	const { styles, config } = theme ?? defaultAlertTheme

	let wnode = $derived(renderAlert(
		{ variant, title, message },
		{ styles, config }
	))
</script>

<wolfie-box use:mountWNode={wnode}></wolfie-box>
