// packages/react/src/components/MultiSelect/MultiSelectOption.tsx
import type { ReactNode } from 'react'
import figures from 'figures'
import { Box } from '../Box'
import { Text } from '../Text'
import { useComponentTheme } from '../../theme/theme'
import type { Theme } from './theme'

//#region Types
export type IMultiSelectOptionProps = {
	/**
	 * Determines if option is focused.
	 */
	isFocused: boolean

	/**
	 * Determines if option is selected.
	 */
	isSelected: boolean

	/**
	 * Option label.
	 */
	children: ReactNode
}
//#endregion Types

//#region Component
export function MultiSelectOption({
	isFocused,
	isSelected,
	children,
}: IMultiSelectOptionProps) {
	const { styles } = useComponentTheme<Theme>('MultiSelect')

	return (
		<Box {...styles.option({ isFocused })}>
			{isFocused && <Text {...styles.focusIndicator()}>{figures.pointer}</Text>}

			<Text {...styles.label({ isFocused, isSelected })}>{children}</Text>

			{isSelected && (
				<Text {...styles.selectedIndicator()}>{figures.tick}</Text>
			)}
		</Box>
	)
}
//#endregion Component

// packages/svelte/src/components/MultiSelectOption.svelte
<script lang="ts">
	import type { Snippet } from 'svelte'
	import figures from 'figures'
	import Box from './Box.svelte'
	import Text from './Text.svelte'
	import { useComponentTheme } from '../theme/index.js'
	import { defaultOptionTheme, type OptionTheme } from './option-theme.js'

	let { isFocused, isSelected, children }: {
		isFocused: boolean
		isSelected: boolean
		children?: Snippet
	} = $props()

	const theme = useComponentTheme<OptionTheme>('MultiSelectOption')
	const { styles } = theme ?? defaultOptionTheme
</script>

<Box {...styles.option({ isFocused })}>
	{#if isFocused}
		<Text {...styles.focusIndicator()}>{figures.pointer}</Text>
	{/if}
	<Text {...styles.label({ isFocused, isSelected })}>
		{#if children}
			{@render children()}
		{/if}
	</Text>
	{#if isSelected}
		<Text {...styles.selectedIndicator()}>{figures.tick}</Text>
	{/if}
</Box>
