// packages/solid/src/components/Static.tsx
import { createSignal, createComputed, For, type JSX } from 'solid-js'
import type { Styles } from '@wolf-tui/core'

//#region Types
export interface StaticProps<T> {
	items: T[]
	style?: Styles
	children: (item: T, index: number) => JSX.Element
}
//#endregion Types

//#region Default Styles
const staticStyles: Partial<Styles> = {
	position: 'absolute',
	flexDirection: 'column',
}
//#endregion Default Styles

export function Static<T>(props: StaticProps<T>) {
	const [index, setIndex] = createSignal(0)

	// Track items length changes synchronously
	createComputed(() => {
		setIndex(props.items.length)
	})

	const itemsToRender = () => props.items.slice(index())

	return (
		<wolfie-box internal_static style={{ ...staticStyles, ...props.style }}>
			<For each={itemsToRender()}>
				{(item, i) => props.children(item, index() + i())}
			</For>
		</wolfie-box>
	)
}

export type { StaticProps as Props, StaticProps as IProps }

// packages/svelte/src/components/Static.svelte
<script lang="ts" generics="T">
	import type { Styles } from '@wolf-tui/core'
	import type { Snippet } from 'svelte'
	import { wolfieProps } from '../renderer/wolfie-action.js'

	//#region Default Styles
	const staticStyles: Partial<Styles> = {
		position: 'absolute',
		flexDirection: 'column',
	}
	//#endregion Default Styles

	let { items, style, children }: {
		items: T[]
		style?: Styles
		children: Snippet<[T, number]>
	} = $props()

	// Track the index offset — only render newly-added items
	let renderedCount = $state(0)

	$effect(() => {
		// Update rendered count when items length changes
		renderedCount = items.length
	})

	let itemsToRender = $derived(items.slice(renderedCount))
	let fullStyle = $derived({ ...staticStyles, ...style })
</script>

<wolfie-box use:wolfieProps={{ style: fullStyle, internal_static: true }}>
	{#each itemsToRender as item, i}
		{@render children(item, renderedCount + i)}
	{/each}
</wolfie-box>
