// packages/react/src/components/ui/Alert.tsx
import { type ReactNode } from 'react'
import Box, { type Props as BoxProps } from '../Box'
import Text, { type Props as TextProps } from '../Text'
import { useComponentTheme, type ComponentTheme } from '../../theme/theme'
import figures from 'figures'

//#region Types
export type AlertVariant = 'info' | 'success' | 'error' | 'warning'

export type AlertProps = {
	/**
	 * Message.
	 */
	readonly children: ReactNode

	/**
	 * Variant, which determines the color of the alert.
	 */
	readonly variant: AlertVariant

	/**
	 * Title to show above the message.
	 */
	readonly title?: string
}

type AlertTheme = {
	styles: {
		container: (props: { variant: AlertVariant }) => Partial<BoxProps>
		iconContainer: () => Partial<BoxProps>
		icon: (props: { variant: AlertVariant }) => Partial<TextProps>
		content: () => Partial<BoxProps>
		title: () => Partial<TextProps>
		message: () => Partial<TextProps>
	}
	config: (props: { variant: AlertVariant }) => {
		icon: string
	}
}
//#endregion Types

//#region Theme
const colorByVariant: Record<AlertVariant, string> = {
	info: 'blue',
	success: 'green',
	error: 'red',
	warning: 'yellow',
}

const iconByVariant: Record<AlertVariant, string> = {
	info: figures.info,
	success: figures.tick,
	error: figures.cross,
	warning: figures.warning,
}

export const alertTheme = {
	styles: {
		container: ({ variant }: { variant: AlertVariant }): Partial<BoxProps> => ({
			style: {
				flexGrow: 1,
				borderStyle: 'round',
				borderColor: colorByVariant[variant],
				gap: 1,
				paddingX: 1,
			},
		}),
		iconContainer: (): Partial<BoxProps> => ({
			style: {
				flexShrink: 0,
			},
		}),
		icon: ({ variant }: { variant: AlertVariant }): Partial<TextProps> => ({
			style: {
				color: colorByVariant[variant],
			},
		}),
		content: (): Partial<BoxProps> => ({
			style: {
				flexShrink: 1,
				flexGrow: 1,
				minWidth: 0,
				flexDirection: 'column',
				gap: 1,
			},
		}),
		title: (): Partial<TextProps> => ({
			style: {
				fontWeight: 'bold',
			},
		}),
		message: (): Partial<TextProps> => ({}),
	},
	config({ variant }: { variant: AlertVariant }) {
		return { icon: iconByVariant[variant] }
	},
} satisfies ComponentTheme
//#endregion Theme

//#region Component
export function Alert({ children, variant, title }: AlertProps) {
	const { styles, config } = useComponentTheme<AlertTheme>('Alert')

	return (
		<Box {...styles.container({ variant })}>
			<Box {...styles.iconContainer()}>
				<Text {...styles.icon({ variant })}>{config({ variant }).icon}</Text>
			</Box>

			<Box {...styles.content()}>
				{title && <Text {...styles.title()}>{title}</Text>}
				<Text {...styles.message()}>{children}</Text>
			</Box>
		</Box>
	)
}
//#endregion Component

// packages/angular/src/components/alert/alert.component.ts
import type { OnInit, OnDestroy } from '@angular/core'
import {
	Component,
	Input,
	ChangeDetectionStrategy,
	signal,
	computed,
	inject,
} from '@angular/core'
import type { Styles } from '@wolfie/core'
import figures from 'figures'
import { BoxComponent } from '../box/box.component'
import { TextComponent } from '../text/text.component'
import {
	THEME_CONTEXT,
	useComponentTheme,
	type IComponentTheme,
} from '../../theme'

//#region Types
export type AlertVariant = 'info' | 'success' | 'error' | 'warning'

export interface AlertProps {
	/**
	 * Variant, which determines the color of the alert.
	 */
	variant: AlertVariant

	/**
	 * Title to show above the message.
	 */
	title?: string
}
//#endregion Types

//#region Theme
const colorByVariant: Record<AlertVariant, string> = {
	info: 'blue',
	success: 'green',
	error: 'red',
	warning: 'yellow',
}

const iconByVariant: Record<AlertVariant, string> = {
	info: figures.info,
	success: figures.tick,
	error: figures.cross,
	warning: figures.warning,
}

export const alertTheme: IComponentTheme = {
	styles: {
		container: (variant: AlertVariant): Partial<Styles> => ({
			flexGrow: 1,
			borderStyle: 'round',
			borderColor: colorByVariant[variant],
			gap: 1,
			paddingX: 1,
		}),
		iconContainer: (): Partial<Styles> => ({
			flexShrink: 0,
		}),
		icon: (variant: AlertVariant): Partial<Styles> => ({
			color: colorByVariant[variant],
		}),
		content: (): Partial<Styles> => ({
			flexShrink: 1,
			flexGrow: 1,
			minWidth: 0,
			flexDirection: 'column',
			gap: 1,
		}),
		title: (): Partial<Styles> => ({
			fontWeight: 'bold',
		}),
		message: (): Partial<Styles> => ({}),
	},
	config: (variant: AlertVariant) => ({
		icon: iconByVariant[variant],
	}),
}
//#endregion Theme

//#region AlertComponent
/**
 * `<w-alert>` displays an alert message with different variants (info, success, error, warning).
 */
@Component({
	selector: 'w-alert',
	standalone: true,
	imports: [BoxComponent, TextComponent],
	template: `
		<w-box [style]="containerStyle()">
			<w-box [style]="iconContainerStyle()">
				<w-text [style]="iconStyle()">{{ icon() }}</w-text>
			</w-box>

			<w-box [style]="contentStyle()">
				@if (title) {
					<w-text [style]="titleStyle()">{{ title }}</w-text>
				}
				<w-text [style]="messageStyle()"><ng-content /></w-text>
			</w-box>
		</w-box>
	`,
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AlertComponent implements OnInit, OnDestroy {
	//#region Inputs
	@Input({ required: true }) variant!: AlertVariant
	@Input() title?: string
	//#endregion Inputs

	//#region Theme
	private readonly theme = inject(THEME_CONTEXT)
	private readonly componentTheme = computed(
		() => useComponentTheme<IComponentTheme>(this.theme, 'Alert') ?? alertTheme
	)
	//#endregion Theme

	//#region Internal State
	private _variant = signal<AlertVariant>('info')
	//#endregion Internal State

	//#region Computed Properties
	readonly containerStyle = computed(
		() =>
			this.componentTheme().styles?.container?.(this._variant()) ??
			alertTheme.styles!.container(this._variant())
	)
	readonly iconContainerStyle = computed(
		() =>
			this.componentTheme().styles?.iconContainer?.() ??
			alertTheme.styles!.iconContainer()
	)
	readonly iconStyle = computed(
		() =>
			this.componentTheme().styles?.icon?.(this._variant()) ??
			alertTheme.styles!.icon(this._variant())
	)
	readonly contentStyle = computed(
		() =>
			this.componentTheme().styles?.content?.() ?? alertTheme.styles!.content()
	)
	readonly titleStyle = computed(
		() => this.componentTheme().styles?.title?.() ?? alertTheme.styles!.title()
	)
	readonly messageStyle = computed(
		() =>
			this.componentTheme().styles?.message?.() ?? alertTheme.styles!.message()
	)
	readonly icon = computed(
		() =>
			(this.componentTheme().config?.(this._variant()) as { icon: string })
				?.icon ?? alertTheme.config!(this._variant()).icon
	)
	//#endregion Computed Properties

	//#region Lifecycle
	ngOnInit(): void {
		this._variant.set(this.variant)
	}

	ngOnDestroy(): void {}

	ngOnChanges(): void {
		this._variant.set(this.variant)
	}
	//#endregion Lifecycle
}
//#endregion AlertComponent
