// packages/svelte/src/components/SelectOption.svelte
<script lang="ts">
	import type { Snippet } from 'svelte'
	import figures from 'figures'
	import Box from './Box.svelte'
	import Text from './Text.svelte'
	import { useComponentTheme } from '../theme/index.js'
	import { defaultOptionTheme, type OptionTheme } from './option-theme.js'

	let { isFocused, isSelected, children }: {
		isFocused: boolean
		isSelected: boolean
		children?: Snippet
	} = $props()

	const theme = useComponentTheme<OptionTheme>('SelectOption')
	const { styles } = theme ?? defaultOptionTheme
</script>

<Box {...styles.option({ isFocused })}>
	{#if isFocused}
		<Text {...styles.focusIndicator()}>{figures.pointer}</Text>
	{/if}
	<Text {...styles.label({ isFocused, isSelected })}>
		{#if children}
			{@render children()}
		{/if}
	</Text>
	{#if isSelected}
		<Text {...styles.selectedIndicator()}>{figures.tick}</Text>
	{/if}
</Box>

// packages/react/src/components/ui/Select/SelectOption.tsx
import type { ReactNode } from 'react'
import figures from 'figures'
import Box from '../../Box.js'
import Text from '../../Text.js'
import { useComponentTheme } from '../../../theme/theme.js'
import type { Theme } from './theme.js'

//#region Types
export type SelectOptionProps = {
	/**
	 * Determines if option is focused.
	 */
	readonly isFocused: boolean

	/**
	 * Determines if option is selected.
	 */
	readonly isSelected: boolean

	/**
	 * Option label.
	 */
	readonly children: ReactNode
}
//#endregion Types

//#region Component
export function SelectOption({
	isFocused,
	isSelected,
	children,
}: SelectOptionProps) {
	const { styles } = useComponentTheme<Theme>('Select')

	return (
		<Box {...styles.option({ isFocused })}>
			{isFocused && (
				<Text {...styles.focusIndicator()}>{figures.pointer}</Text>
			)}

			<Text {...styles.label({ isFocused, isSelected })}>{children}</Text>

			{isSelected && (
				<Text {...styles.selectedIndicator()}>{figures.tick}</Text>
			)}
		</Box>
	)
}
//#endregion Component
