// examples/react_invaders/src/hooks/useTerminalSize.ts
import { useState, useEffect } from 'react'
import { useStdout } from '@wolf-tui/react'

export type TerminalSize = {
	width: number
	height: number
}

export function useTerminalSize(): TerminalSize {
	const { stdout } = useStdout()

	const [size, setSize] = useState<TerminalSize>({
		width: stdout.columns ?? 80,
		height: stdout.rows ?? 24,
	})

	useEffect(() => {
		const handleResize = () => {
			setSize({
				width: stdout.columns ?? 80,
				height: stdout.rows ?? 24,
			})
		}

		stdout.on('resize', handleResize)
		return () => {
			stdout.off('resize', handleResize)
		}
	}, [stdout])

	return size
}

// examples/solid_invaders/src/composables/useTerminalSize.ts
import { createSignal, onCleanup, type Accessor } from 'solid-js'
import { useStdout } from '@wolf-tui/solid'

//#region Types
export type TerminalSize = {
	width: Accessor<number>
	height: Accessor<number>
}
//#endregion Types

//#region Composable
export function useTerminalSize(): TerminalSize {
	const { stdout } = useStdout()

	const [width, setWidth] = createSignal(stdout.columns ?? 80)
	const [height, setHeight] = createSignal(stdout.rows ?? 24)

	const handleResize = () => {
		setWidth(stdout.columns ?? 80)
		setHeight(stdout.rows ?? 24)
	}

	// Register immediately — onMount doesn't fire in universal renderer
	stdout.on('resize', handleResize)

	onCleanup(() => {
		stdout.off('resize', handleResize)
	})

	return { width, height }
}
//#endregion Composable
