// examples/react_invaders/src/components/FocusableItem.tsx
import type { ReactNode } from 'react'
import { Box, Text, useFocus } from '@wolf-tui/react'

//#region Types
type FocusableItemProps = {
	id?: string
	children: ReactNode
	onSelect?: () => void
	autoFocus?: boolean
}
//#endregion Types

//#region Component
export function FocusableItem({
	id,
	children,
	onSelect: _onSelect,
	autoFocus = false,
}: FocusableItemProps) {
	const { isFocused } = useFocus({ id, autoFocus })

	return (
		<Box
			className={isFocused ? 'bg-blue p-x-2' : 'p-x-2'}
			style={{ cursor: 'pointer' }}
		>
			<Text className={isFocused ? 'text-white font-bold' : 'text-gray'}>
				{isFocused ? '> ' : '  '}
				{children}
			</Text>
		</Box>
	)
}
//#endregion Component

// examples/svelte_esbuild/src/screens/FocusableItem.svelte
<script>
	import { Box, Text, useFocus } from '@wolf-tui/svelte'

	let { id, label, color, autoFocus = false, isActive = true } = $props()

	const { isFocused } = useFocus({
		id: id,
		autoFocus: autoFocus,
		isActive: () => isActive,
	})
</script>

<Box className={[
	'p-1',
	isFocused() ? 'border-double' : 'border-single',
	isFocused() ? `border-${color}` : 'border-gray',
].join(' ')}>
	<Text className={
		isFocused()
			? `text-${color} font-bold`
			: isActive
				? 'text-white'
				: 'text-gray'
	}>
		{isFocused() ? '> ' : '  '}{label}{isFocused() ? ' (focused)' : ''}{!isActive ? ' (disabled)' : ''}
	</Text>
</Box>
