// packages/solid/src/components/Box.tsx
import { useContext, type JSX } from 'solid-js'
import type { Styles } from '@wolfie/core'
import { AccessibilityCtx, BackgroundCtx } from '../context/symbols'
import { resolveClassName, type ClassNameValue } from '../styles'

//#region Types
type AriaRole =
	| 'button'
	| 'checkbox'
	| 'combobox'
	| 'list'
	| 'listbox'
	| 'listitem'
	| 'menu'
	| 'menuitem'
	| 'option'
	| 'progressbar'
	| 'radio'
	| 'radiogroup'
	| 'tab'
	| 'tablist'
	| 'table'
	| 'textbox'
	| 'timer'
	| 'toolbar'

type AriaState = {
	busy?: boolean
	checked?: boolean
	disabled?: boolean
	expanded?: boolean
	multiline?: boolean
	multiselectable?: boolean
	readonly?: boolean
	required?: boolean
	selected?: boolean
}

export interface BoxProps {
	className?: ClassNameValue
	style?: Styles
	'aria-label'?: string
	'aria-hidden'?: boolean
	'aria-role'?: AriaRole
	'aria-state'?: AriaState
	children?: JSX.Element
}
//#endregion Types

//#region Default Styles
const defaultBoxStyles: Partial<Styles> = {
	flexWrap: 'nowrap',
	flexDirection: 'row',
	flexGrow: 0,
	flexShrink: 1,
}
//#endregion Default Styles

export function Box(props: BoxProps) {
	const accessibility = useContext(AccessibilityCtx)
	const inheritedBackgroundColor = useContext(BackgroundCtx)

	const resolvedStyles = () => {
		const style = props.style ?? {}
		const resolved = resolveClassName(props.className)
		return { ...resolved, ...style }
	}

	const backgroundColor = () => {
		const s = resolvedStyles()
		return s.backgroundColor ?? inheritedBackgroundColor?.()
	}

	return (
		<BackgroundCtx.Provider value={backgroundColor}>
			{(() => {
				const isScreenReaderEnabled = accessibility?.isScreenReaderEnabled
				const ariaLabel = props['aria-label']
				const ariaHidden = props['aria-hidden']
				const ariaRole = props['aria-role']
				const ariaState = props['aria-state']

				if (isScreenReaderEnabled && ariaHidden) {
					return null
				}

				const style = resolvedStyles()
				const bgColor = backgroundColor()

				const label = ariaLabel ? (
					<wolfie-text>{ariaLabel}</wolfie-text>
				) : undefined

				return (
					<wolfie-box
						style={{
							backgroundColor: bgColor,
							overflowX: style.overflowX ?? style.overflow ?? 'visible',
							overflowY: style.overflowY ?? style.overflow ?? 'visible',
							...defaultBoxStyles,
							...style,
						}}
						internal_accessibility={{
							role: ariaRole,
							state: ariaState,
						}}
					>
						{isScreenReaderEnabled && label ? label : props.children}
					</wolfie-box>
				)
			})()}
		</BackgroundCtx.Provider>
	)
}

export type { BoxProps as Props, BoxProps as IProps }

// packages/react/src/components/Box.tsx
import React, {forwardRef, useContext, type PropsWithChildren} from 'react';
import {type Except} from 'type-fest';
import {type Styles, type DOMElement} from '@wolfie/core';
import {accessibilityContext} from './AccessibilityContext.js';
import {backgroundContext} from './BackgroundContext.js';

export type Props = Except<Styles, 'textWrap'> & {
	/**
	A label for the element for screen readers.
	*/
	readonly 'aria-label'?: string;

	/**
	Hide the element from screen readers.
	*/
	readonly 'aria-hidden'?: boolean;

	/**
	The role of the element.
	*/
	readonly 'aria-role'?:
		| 'button'
		| 'checkbox'
		| 'combobox'
		| 'list'
		| 'listbox'
		| 'listitem'
		| 'menu'
		| 'menuitem'
		| 'option'
		| 'progressbar'
		| 'radio'
		| 'radiogroup'
		| 'tab'
		| 'tablist'
		| 'table'
		| 'textbox'
		| 'timer'
		| 'toolbar';

	/**
	The state of the element.
	*/
	readonly 'aria-state'?: {
		readonly busy?: boolean;
		readonly checked?: boolean;
		readonly disabled?: boolean;
		readonly expanded?: boolean;
		readonly multiline?: boolean;
		readonly multiselectable?: boolean;
		readonly readonly?: boolean;
		readonly required?: boolean;
		readonly selected?: boolean;
	};
};

/**
`<Box>` is an essential Ink component to build your layout. It's like `<div style="display: flex">` in the browser.
*/
const Box = forwardRef<DOMElement, PropsWithChildren<Props>>(
	(
		{
			children,
			backgroundColor,
			'aria-label': ariaLabel,
			'aria-hidden': ariaHidden,
			'aria-role': role,
			'aria-state': ariaState,
			...style
		},
		ref,
	) => {
		const {isScreenReaderEnabled} = useContext(accessibilityContext);
		const label = ariaLabel ? <ink-text>{ariaLabel}</ink-text> : undefined;
		if (isScreenReaderEnabled && ariaHidden) {
			return null;
		}

		const boxElement = (
			<ink-box
				ref={ref}
				style={{
					flexWrap: 'nowrap',
					flexDirection: 'row',
					flexGrow: 0,
					flexShrink: 1,
					...style,
					backgroundColor,
					overflowX: style.overflowX ?? style.overflow ?? 'visible',
					overflowY: style.overflowY ?? style.overflow ?? 'visible',
				}}
				internal_accessibility={{
					role,
					state: ariaState,
				}}
			>
				{isScreenReaderEnabled && label ? label : children}
			</ink-box>
		);

		// If this Box has a background color, provide it to children via context
		if (backgroundColor) {
			return (
				<backgroundContext.Provider value={backgroundColor}>
					{boxElement}
				</backgroundContext.Provider>
			);
		}

		return boxElement;
	},
);

Box.displayName = 'Box';

export default Box;
