// examples/svelte_vite/src/screens/StyleDemo.svelte
<script>
	import { Box, Text } from '@wolf-tui/svelte'
	import buttonStyles from '../styles/Button.module.css'
	import cardStyles from '../styles/Card.module.css'
	import ScssSection from './ScssSection.svelte'
	import LessSection from './LessSection.svelte'
	import StylusSection from './StylusSection.svelte'
</script>

<Box className="flex-col w-full">
	<!-- Tailwind Section -->
	<Box className="border-double border-yellow p-1 mb-1 flex-col w-full">
		<Text className="text-[cyan]">
			Tailwind: border-double + arbitrary text-[cyan]
		</Text>
	</Box>

	<!-- Preprocessor Sections (each in own component — Svelte allows 1 style block) -->
	<ScssSection />
	<LessSection />
	<StylusSection />

	<!-- Scoped Section -->
	<Box className="scoped-box flex-col mb-1 w-full">
		<Text className="scoped-text">Scoped Flavor</Text>
		<Text className="text-muted">Scoped styles (Svelte default)</Text>
	</Box>

	<!-- CSS Modules Section -->
	<Box className="{cardStyles.card} flex-col mb-1 w-full">
		<Text className={cardStyles.cardTitle}>CSS Modules Flavor</Text>
		<Text className="text-muted">Scoped styles from Card.module.css</Text>
	</Box>

	<!-- Buttons Mix -->
	<Box className="flex-row gap-2 w-full">
		<Box className={buttonStyles.button}>
			<Text className={buttonStyles.text}>Module Btn</Text>
		</Box>
		<Box className="bg-blue-600 p-x-2">
			<Text className="text-[#ffffff]">Tailwind Btn</Text>
		</Box>
	</Box>
</Box>

<style>
.scoped-box {
	border-style: single;
	border-color: blue;
	padding: 1;
}

.scoped-text {
	color: blue;
	font-weight: bold;
}

.text-muted {
	color: gray;
}
</style>

// examples/vue_esbuild/src/screens/StyleDemo.vue
<template>
	<Box class="flex-col w-full">
		<!-- Tailwind Section -->
		<Box class="border-double border-yellow p-1 mb-1 flex-col w-full">
			<Text class="text-[cyan]">
				Tailwind: border-double + arbitrary text-[cyan]
			</Text>
		</Box>

		<!-- SCSS Section -->
		<Box class="card flex-col mb-1 w-full">
			<Text class="card-title">SCSS Flavor</Text>
			<Text class="text-muted"> Nested selectors from style lang="scss" </Text>
		</Box>

		<!-- LESS Section -->
		<Box class="less-box flex-col mb-1 w-full">
			<Text class="less-text">LESS Flavor</Text>
			<Text class="text-muted"> Nesting from style lang="less" </Text>
		</Box>

		<!-- Stylus Section -->
		<Box class="stylus-box flex-col mb-1 w-full">
			<Text class="stylus-text">Stylus Flavor</Text>
			<Text class="text-muted">Indentation-based style lang="stylus"</Text>
		</Box>

		<!-- Scoped Section (Bold/Blue) -->
		<Box class="scoped-box flex-col mb-1 w-full">
			<Text class="scoped-text">Scoped Flavor</Text>
			<Text class="text-muted"
				>Scoped styles from style lang="scss" scoped</Text
			>
		</Box>

		<!-- CSS Modules Section -->
		<Box :class="[cardStyles.card, 'flex-col mb-1 w-full']">
			<Text :class="cardStyles.cardTitle">CSS Modules Flavor</Text>
			<Text class="text-muted">Scoped styles from Card.module.css</Text>
		</Box>

		<!-- SFC Module Style Section -->
		<Box :class="[$style.moduleBox, 'flex-col mb-1 w-full']">
			<Text :class="$style.moduleText">SFC Module Style</Text>
			<Text class="text-muted">Scoped via style module</Text>
		</Box>

		<!-- Buttons Mix -->
		<Box class="flex-row gap-2 w-full">
			<Box class="btn primary">
				<Text>SCSS Btn</Text>
			</Box>
			<Box :class="buttonStyles.button">
				<Text :class="buttonStyles.text">Module Btn</Text>
			</Box>
			<Box class="bg-blue-600 p-x-2">
				<Text class="text-white">Tailwind Btn</Text>
			</Box>
		</Box>
	</Box>
</template>

<script setup lang="ts">
import { Box, Text } from '@wolf-tui/vue'
import buttonStyles from '../styles/Button.module.css'
import cardStyles from '../styles/Card.module.css'
</script>

<!-- Global utility classes -->
<style>
.text-base {
	color: white;
}

.text-muted {
	color: gray;
}
</style>

<!-- SCSS styles with nesting -->
<style lang="scss">
$primary: magenta;

.card {
	border-style: single;
	padding: 1;
	border-color: $primary;

	.card-title {
		color: $primary;
		font-weight: bold;
	}
}

.btn {
	padding-x: 2;
	padding-y: 1;
	border-style: single;
	border-color: $primary;

	&.primary {
		border-color: $primary;
	}
}
</style>

<!-- LESS styles with nesting -->
<style lang="less">
@green: green;

.less-box {
	border-style: single;
	border-color: @green;
	padding: 1;

	.less-text {
		color: @green;
		font-weight: bold;
	}
}
</style>

<!-- Stylus styles with indentation -->
<style lang="stylus">
$yellow = yellow

.stylus-box
	border-style single
	border-color $yellow
	padding 1

	.stylus-text
		color $yellow
		font-style italic
</style>

<!-- SFC Module styles -->
<style module>
.moduleBox {
	border-style: double;
	border-color: white;
	padding: 1;
}

.moduleText {
	color: white;
	font-weight: bold;
}
</style>

<style lang="scss" scoped>
.scoped-box {
	border-style: single;
	border-color: blue;
	padding: 1;

	.scoped-text {
		color: blue;
		font-weight: bold;
	}
}
</style>
