// examples/react_invaders/src/App.tsx
import { useState } from 'react'
import {
	Box,
	ThemeProvider,
	ErrorOverview,
	useStderr,
	useIsScreenReaderEnabled,
} from '@wolf-tui/react'
import { invadersTheme } from './theme'
import { useInvaders } from './hooks/useInvaders'
import { useTerminalSize } from './hooks/useTerminalSize'
import { Menu } from './screens/Menu'
import { Game } from './screens/Game'
import { GameOver } from './screens/GameOver'
import { HighScores } from './screens/HighScores'
import { Settings } from './screens/Settings'
import { Help } from './screens/Help'

//#region Error Boundary
function ErrorBoundary({ children }: { children: React.ReactNode }) {
	const [error] = useState<Error | null>(null)
	const { write: writeStderr } = useStderr()

	if (error) {
		// Log to stderr for debugging
		writeStderr(`Error: ${error.message}\n${error.stack ?? ''}\n`)

		return <ErrorOverview error={error} />
	}

	// In a real app, we'd use React error boundaries
	// For now, just render children
	return <>{children}</>
}
//#endregion Error Boundary

//#region App Component
function AppContent() {
	const { width: termWidth, height: termHeight } = useTerminalSize()
	const {
		state,
		navigate,
		startGame,
		tick,
		movePlayer,
		shoot,
		alienShoot,
		pause,
		nextWave,
		updateSettings,
		restart,
	} = useInvaders(termWidth, termHeight)

	const isScreenReaderEnabled = useIsScreenReaderEnabled()

	// Announce screen changes for accessibility
	if (isScreenReaderEnabled) {
		// Screen reader would announce the current screen
	}

	return (
		<Box style={{ flexDirection: 'column', minHeight: '100%' }}>
			{state.screen === 'menu' && (
				<Menu onNavigate={navigate} onStartGame={startGame} />
			)}

			{state.screen === 'game' && (
				<Game
					state={state}
					onTick={tick}
					onMovePlayer={movePlayer}
					onShoot={shoot}
					onAlienShoot={alienShoot}
					onPause={pause}
					onNextWave={nextWave}
					onNavigate={navigate}
				/>
			)}

			{state.screen === 'gameover' && (
				<GameOver
					score={state.score}
					wave={state.wave}
					onNavigate={navigate}
					onRestart={restart}
				/>
			)}

			{state.screen === 'highscores' && (
				<HighScores score={state.score} onNavigate={navigate} />
			)}

			{state.screen === 'settings' && (
				<Settings
					settings={state.settings}
					onUpdateSettings={updateSettings}
					onNavigate={navigate}
				/>
			)}

			{state.screen === 'help' && <Help onNavigate={navigate} />}
		</Box>
	)
}
//#endregion App Component

//#region Main App
export function App() {
	return (
		<ThemeProvider theme={invadersTheme}>
			<ErrorBoundary>
				<AppContent />
			</ErrorBoundary>
		</ThemeProvider>
	)
}
//#endregion Main App

// examples/vue_invaders/src/App.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Box, provideTheme, ErrorOverview, useStderr } from '@wolf-tui/vue'
import { invadersTheme } from './theme'
import { useInvaders } from './composables/useInvaders'
import { useTerminalSize } from './composables/useTerminalSize'

// Load screens
import Menu from './screens/Menu.vue'
import Game from './screens/Game.vue'
import GameOver from './screens/GameOver.vue'
import HighScores from './screens/HighScores.vue'
import Settings from './screens/Settings.vue'
import Help from './screens/Help.vue'

//#region Theme Provider
provideTheme(invadersTheme)
//#endregion Theme Provider

//#region Error Handling
const error = ref<Error | null>(null)
const { write: writeStderr } = useStderr()

function handleError(err: Error) {
	error.value = err
	writeStderr(`Error: ${err.message}\n${err.stack ?? ''}\n`)
}
//#endregion Error Handling

//#region Game State
const { width: termWidth, height: termHeight } = useTerminalSize()
const {
	state,
	navigate,
	startGame,
	tick,
	movePlayer,
	shoot,
	alienShoot,
	pause,
	nextWave,
	updateSettings,
	restart,
} = useInvaders(termWidth, termHeight)
//#endregion Game State
</script>

<template>
	<ErrorOverview v-if="error" :error="error" /><Menu
		v-else-if="state.screen === 'menu'"
		:on-navigate="navigate"
		:on-start-game="startGame"
	/><Game
		v-else-if="state.screen === 'game'"
		:state="state"
		:on-tick="tick"
		:on-move-player="movePlayer"
		:on-shoot="shoot"
		:on-alien-shoot="alienShoot"
		:on-pause="pause"
		:on-next-wave="nextWave"
		:on-navigate="navigate"
	/><GameOver
		v-else-if="state.screen === 'gameover'"
		:score="state.score"
		:wave="state.wave"
		:on-navigate="navigate"
		:on-restart="restart"
	/><HighScores
		v-else-if="state.screen === 'highscores'"
		:score="state.score"
		:on-navigate="navigate"
	/><Settings
		v-else-if="state.screen === 'settings'"
		:settings="state.settings"
		:on-update-settings="updateSettings"
		:on-navigate="navigate"
	/><Help v-else-if="state.screen === 'help'" :on-navigate="navigate" />
</template>
