// examples/svelte_esbuild/src/screens/FocusDemo.svelte
<script>
	import { Box, Text, useInput, useFocusManager } from '@wolfie/svelte'
	import FocusableItem from './FocusableItem.svelte'

	const items = [
		{ id: 'item-1', label: 'First Item', color: 'red' },
		{ id: 'item-2', label: 'Second Item', color: 'green' },
		{ id: 'item-3', label: 'Third Item', color: 'blue' },
		{ id: 'item-4', label: 'Fourth Item', color: 'yellow' },
	]

	let item2Active = $state(true)
	const { focus } = useFocusManager()

	useInput((input) => {
		const num = parseInt(input)
		if (num >= 1 && num <= 4) {
			focus(`item-${num}`)
		}
		if (input === 'd') {
			item2Active = !item2Active
		}
	})
</script>

<Box className="flex-col gap-1 w-full">
	<Text className="text-gray">Tab/Shift+Tab to navigate between items</Text>

	<!-- Focusable Items -->
	<Box className="flex-col gap-1">
		{#each items as item, i}
			<FocusableItem
				id={item.id}
				label={item.label}
				color={item.color}
				autoFocus={i === 0}
				isActive={item.id === 'item-2' ? item2Active : true}
			/>
		{/each}
	</Box>

	<!-- Focus Controls -->
	<Box className="border-single border-gray p-1 mt-1 flex-col">
		<Text className="font-bold text-cyan">Focus Controls:</Text>
		<Text className="text-gray">Press 1-4 to focus item directly</Text>
		<Text className="text-gray">Press 'd' to disable/enable item 2</Text>
		<Text className="text-gray mt-1">Item 2 active: {item2Active ? 'Yes' : 'No'}</Text>
	</Box>
</Box>

// examples/vue_vite/screens/FocusDemo.vue
<template>
	<Box class="flex-col gap-1 w-full">
		<Text class="text-[gray]">Tab/Shift+Tab to navigate between items</Text>

		<!-- Focusable Items -->
		<Box class="flex-col gap-1">
			<FocusableItem
				v-for="(item, i) in items"
				:key="item.id"
				:id="item.id"
				:label="item.label"
				:color="item.color"
				:auto-focus="i === 0"
			/>
		</Box>

		<!-- Focus Controls -->
		<Box class="border-single border-[gray] p-1 mt-1 flex-col">
			<Text class="font-bold text-[cyan]">Focus Controls:</Text>
			<Text class="text-[gray]">Press 1-4 to focus item directly</Text>
			<Text class="text-[gray]">Press 'd' to disable/enable item 2</Text>
			<Text class="text-[gray] mt-1"
				>Item 2 active: {{ item2Active ? 'Yes' : 'No' }}</Text
			>
		</Box>
	</Box>
</template>

<script setup lang="ts">
import { ref, computed, defineComponent, h } from 'vue'
import { Box, Text, useInput, useFocus, useFocusManager } from '@wolfie/vue'

const items = [
	{ id: 'item-1', label: 'First Item', color: 'red' },
	{ id: 'item-2', label: 'Second Item', color: 'green' },
	{ id: 'item-3', label: 'Third Item', color: 'blue' },
	{ id: 'item-4', label: 'Fourth Item', color: 'yellow' },
]

const item2Active = ref(true)
const { focus } = useFocusManager()

// Handle direct focus via number keys and toggle
useInput((input) => {
	const num = parseInt(input)
	if (num >= 1 && num <= 4) {
		focus(`item-${num}`)
	}
	if (input === 'd') {
		item2Active.value = !item2Active.value
	}
})

// Focusable item component
const FocusableItem = defineComponent({
	props: {
		id: { type: String, required: true },
		label: { type: String, required: true },
		color: { type: String, required: true },
		autoFocus: { type: Boolean, default: false },
	},
	setup(props) {
		const isActive = computed(() => {
			if (props.id === 'item-2') return item2Active.value
			return true
		})

		const { isFocused } = useFocus({
			id: props.id,
			autoFocus: props.autoFocus,
			isActive,
		})

		return () =>
			h(
				Box,
				{
					class: [
						'p-1',
						isFocused.value ? 'border-double' : 'border-single',
						!isActive.value ? 'opacity-50' : '',
					]
						.filter(Boolean)
						.join(' '),
					style: { borderColor: isFocused.value ? props.color : 'gray' },
				},
				() => [
					h(
						Text,
						{
							class: isFocused.value
								? 'font-bold'
								: isActive.value
									? 'text-white'
									: 'text-[gray]',
							style: isFocused.value ? { color: props.color } : {},
						},
						() =>
							`${isFocused.value ? '> ' : '  '}${props.label}${isFocused.value ? ' (focused)' : ''}${!isActive.value ? ' (disabled)' : ''}`
					),
				]
			)
	},
})
</script>
