// packages/react/src/components/Text/index.tsx
import React, { useContext } from 'react'
import chalk from 'chalk'
import { colorize, type Styles } from '@wolfie/core'
import { accessibilityContext } from '../../context/AccessibilityContext'
import { backgroundContext } from '../../context/BackgroundContext'
import { resolveClassName } from '../../styles/index'
import type { IProps } from './types'

/**
This component can display text and change its style to make it bold, underlined, italic, or strikethrough.
*/
export function Text({
	className,
	style = {},
	children,
	'aria-label': ariaLabel,
	'aria-hidden': ariaHidden = false,
}: IProps) {
	const { isScreenReaderEnabled } = useContext(accessibilityContext)
	const inheritedBackgroundColor = useContext(backgroundContext)
	const childrenOrAriaLabel =
		isScreenReaderEnabled && ariaLabel ? ariaLabel : children

	if (childrenOrAriaLabel === undefined || childrenOrAriaLabel === null) {
		return null
	}

	const resolvedClassName = resolveClassName(className)

	const effectiveStyles: Styles = {
		...resolvedClassName,
		...style,
	}

	const effectiveColor = effectiveStyles.color
	const effectiveBackgroundColor = effectiveStyles.backgroundColor
	const effectiveBold = effectiveStyles.fontWeight === 'bold'
	const effectiveItalic = effectiveStyles.fontStyle === 'italic'
	const effectiveUnderline = effectiveStyles.textDecoration === 'underline'
	const effectiveStrikethrough =
		effectiveStyles.textDecoration === 'line-through'
	const effectiveInverse = effectiveStyles.inverse ?? false
	const effectiveWrap = effectiveStyles.textWrap ?? 'wrap'

	const transform = (children: string): string => {
		if (effectiveColor) {
			children = colorize(children, effectiveColor, 'foreground')
		}

		const finalBackgroundColor =
			effectiveBackgroundColor ?? inheritedBackgroundColor
		if (finalBackgroundColor) {
			children = colorize(children, finalBackgroundColor, 'background')
		}

		if (effectiveBold) {
			children = chalk.bold(children)
		}

		if (effectiveItalic) {
			children = chalk.italic(children)
		}

		if (effectiveUnderline) {
			children = chalk.underline(children)
		}

		if (effectiveStrikethrough) {
			children = chalk.strikethrough(children)
		}

		if (effectiveInverse) {
			children = chalk.inverse(children)
		}

		return children
	}

	if (isScreenReaderEnabled && ariaHidden) {
		return null
	}

	return (
		<wolfie-text
			style={{
				...effectiveStyles,
				textWrap: effectiveWrap,
			}}
			internal_transform={transform}
		>
			{isScreenReaderEnabled && ariaLabel ? ariaLabel : children}
		</wolfie-text>
	)
}

export type { IProps as Props } from './types'
export type { IProps } from './types'

// packages/solid/src/components/Text.tsx
import { useContext, type JSX } from 'solid-js'
import chalk from 'chalk'
import { colorize, type Styles } from '@wolfie/core'
import { AccessibilityCtx, BackgroundCtx } from '../context/symbols'
import { resolveClassName, type ClassNameValue } from '../styles'

//#region Types
export interface TextProps {
	className?: ClassNameValue
	style?: Styles
	'aria-label'?: string
	'aria-hidden'?: boolean
	children?: JSX.Element
}
//#endregion Types

export function Text(props: TextProps) {
	const accessibility = useContext(AccessibilityCtx)
	const inheritedBackgroundColor = useContext(BackgroundCtx)

	const effectiveStyles = (): Styles => {
		const resolved = resolveClassName(props.className)
		return { ...resolved, ...(props.style ?? {}) }
	}

	return (() => {
		const ariaLabel = props['aria-label']
		const ariaHidden = props['aria-hidden']
		const isScreenReaderEnabled = accessibility?.isScreenReaderEnabled
		const children =
			isScreenReaderEnabled && ariaLabel ? ariaLabel : props.children

		if (children === undefined || children === null) return null
		if (isScreenReaderEnabled && ariaHidden) return null

		const styles = effectiveStyles()

		const effectiveColor = styles.color
		const effectiveBackgroundColor = styles.backgroundColor
		const effectiveBold = styles.fontWeight === 'bold'
		const effectiveItalic = styles.fontStyle === 'italic'
		const effectiveUnderline = styles.textDecoration === 'underline'
		const effectiveStrikethrough = styles.textDecoration === 'line-through'
		const effectiveInverse = styles.inverse ?? false
		const effectiveWrap = styles.textWrap ?? 'wrap'

		const transform = (text: string): string => {
			let result = text

			if (effectiveColor) {
				result = colorize(result, effectiveColor, 'foreground')
			}

			const finalBackgroundColor =
				effectiveBackgroundColor ?? inheritedBackgroundColor?.()
			if (finalBackgroundColor) {
				result = colorize(result, finalBackgroundColor, 'background')
			}

			if (effectiveBold) result = chalk.bold(result)
			if (effectiveItalic) result = chalk.italic(result)
			if (effectiveUnderline) result = chalk.underline(result)
			if (effectiveStrikethrough) result = chalk.strikethrough(result)
			if (effectiveInverse) result = chalk.inverse(result)

			return result
		}

		return (
			<wolfie-text
				style={{ ...styles, textWrap: effectiveWrap }}
				internal_transform={transform}
			>
				{children}
			</wolfie-text>
		)
	})()
}

export type { TextProps as Props, TextProps as IProps }
