// packages/svelte/src/components/TextInput.svelte
<script lang="ts">
	import {
		renderTextInput,
		defaultTextInputTheme,
		type TextInputRenderTheme,
	} from '@wolf-tui/shared'
	import { mountWNode } from '../wnode/wnode-to-svelte.js'
	import { useComponentTheme } from '../theme/index.js'
	import { useTextInputState } from '../composables/use-text-input-state.svelte.js'
	import { useTextInput } from '../composables/use-text-input.js'

	let {
		isDisabled,
		placeholder,
		defaultValue,
		suggestions,
		onChange,
		onSubmit,
	}: {
		isDisabled?: boolean
		placeholder?: string
		defaultValue?: string
		suggestions?: string[]
		onChange?: (value: string) => void
		onSubmit?: (value: string) => void
	} = $props()

	const state = useTextInputState({ defaultValue, suggestions, onChange, onSubmit })
	const { inputValue } = useTextInput({
		isDisabled: () => isDisabled,
		placeholder,
		state,
	})

	const theme = useComponentTheme<TextInputRenderTheme>('TextInput')
	const { styles } = theme ?? defaultTextInputTheme

	let wnode = $derived(renderTextInput({ inputValue: inputValue() }, { styles }))
</script>

<wolfie-box use:mountWNode={wnode}></wolfie-box>

// packages/solid/src/components/TextInput.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import { useTextInputState } from '../composables/use-text-input-state'
import { useTextInput } from '../composables/use-text-input'
import {
	renderTextInput,
	defaultTextInputTheme,
	type TextInputRenderTheme,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface ITextInputProps {
	isDisabled?: boolean
	placeholder?: string
	defaultValue?: string
	suggestions?: string[]
	onChange?: (value: string) => void
	onSubmit?: (value: string) => void
}
//#endregion Types

//#region Component
export function TextInput(props: ITextInputProps): JSX.Element {
	const [local] = splitProps(props, [
		'isDisabled',
		'placeholder',
		'defaultValue',
		'suggestions',
		'onChange',
		'onSubmit',
	])

	const state = useTextInputState({
		defaultValue: local.defaultValue,
		suggestions: local.suggestions,
		onChange: local.onChange,
		onSubmit: local.onSubmit,
	})

	const { inputValue } = useTextInput({
		isDisabled: () => local.isDisabled,
		placeholder: local.placeholder,
		state,
	})

	const theme = useComponentTheme<TextInputRenderTheme>('TextInput')
	const { styles } = theme ?? defaultTextInputTheme

	// inputValue() is a signal accessor — createMemo tracks it
	const wnode = createMemo(() =>
		renderTextInput({ inputValue: inputValue() }, { styles })
	)

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}
//#endregion Component
