// packages/svelte/src/components/Transform.svelte
<script lang="ts">
	import { getContext, type Snippet } from 'svelte'
	import { wolfieProps } from '../renderer/wolfie-action.js'
	import { ACCESSIBILITY_CTX } from '../context/symbols.js'
	import type { AccessibilityContextValue } from '../context/types.js'

	let { transform, accessibilityLabel, children }: {
		transform: (children: string, index: number) => string
		accessibilityLabel?: string
		children?: Snippet
	} = $props()

	const accessibility = getContext<AccessibilityContextValue | undefined>(ACCESSIBILITY_CTX)

	let showAriaLabel = $derived(accessibility?.isScreenReaderEnabled && accessibilityLabel)
</script>

{#if children || showAriaLabel}
	<wolfie-text use:wolfieProps={{ internal_transform: transform }}>
		{#if showAriaLabel}
			{accessibilityLabel}
		{:else if children}
			{@render children()}
		{/if}
	</wolfie-text>
{/if}

// packages/solid/src/components/Transform.tsx
import { useContext, type JSX } from 'solid-js'
import { AccessibilityCtx } from '../context/symbols'

//#region Types
export interface TransformProps {
	accessibilityLabel?: string
	transform: (children: string, index: number) => string
	children?: JSX.Element
}
//#endregion Types

export function Transform(props: TransformProps) {
	const accessibility = useContext(AccessibilityCtx)

	return (() => {
		if (props.children === undefined || props.children === null) {
			return null
		}

		const isScreenReaderEnabled = accessibility?.isScreenReaderEnabled
		const content =
			isScreenReaderEnabled && props.accessibilityLabel
				? props.accessibilityLabel
				: props.children

		return (
			<wolfie-text internal_transform={props.transform}>{content}</wolfie-text>
		)
	})()
}

export type { TransformProps as Props, TransformProps as IProps }
