// packages/solid/src/components/Badge.tsx
import { type JSX, splitProps, createMemo } from 'solid-js'
import type { Styles } from '@wolf-tui/core'
import {
	renderBadge,
	defaultBadgeTheme,
	type BadgeRenderTheme,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../theme'
import { wNodeToSolid } from '../wnode/wnode-to-solid'

//#region Types
export interface IBadgeProps {
	children: JSX.Element
	color?: string
	style?: Styles
}
//#endregion Types

export function Badge(props: IBadgeProps): JSX.Element {
	const [local] = splitProps(props, ['children', 'color'])

	const theme = useComponentTheme<BadgeRenderTheme>('Badge')
	const { styles } = theme ?? defaultBadgeTheme

	const wnode = createMemo(() => {
		const label = String(local.children ?? '').toUpperCase()
		return renderBadge(
			{ label, color: local.color as Styles['color'] },
			{ styles }
		)
	})

	return (() => wNodeToSolid(wnode())) as unknown as JSX.Element
}

// packages/react/src/components/Badge/Badge.tsx
import { type Styles } from '@wolf-tui/core'
import { type ReactNode } from 'react'
import {
	renderBadge,
	defaultBadgeTheme,
	type BadgeRenderTheme,
} from '@wolf-tui/shared'
import { useComponentTheme } from '../../theme/theme'
import { wNodeToReact } from '../../wnode/wnode-to-react'

//#region Types
export type IBadgeProps = {
	/**
	 * Label.
	 */
	children: ReactNode

	/**
	 * Color.
	 *
	 * @default "magenta"
	 */
	color?: Styles['color']
}
//#endregion Types

//#region Component
export function Badge({ children, color = 'magenta' }: IBadgeProps) {
	const theme = useComponentTheme<BadgeRenderTheme>('Badge')
	const { styles } = theme ?? defaultBadgeTheme

	// Extract string label — Badge displays plain text, not arbitrary nodes.
	const label =
		typeof children === 'string'
			? children.toUpperCase()
			: String(children ?? '')

	return wNodeToReact(renderBadge({ label, color }, { styles }))
}
//#endregion Component
