// packages/react/src/components/TextInput/use-text-input-state.ts
import { useReducer, useCallback, useEffect, useMemo } from 'react'
import {
	textInputReducer,
	createInitialTextInputState,
	findSuggestion,
	type TextInputState as SharedTextInputState,
} from '@wolfie/shared'

//#region Hook Types
export type UseTextInputStateProps = {
	/**
	 * Default input value.
	 */
	defaultValue?: string

	/**
	 * Suggestions to autocomplete the input value.
	 */
	suggestions?: string[]

	/**
	 * Callback when input value changes.
	 */
	onChange?: (value: string) => void

	/**
	 * Callback when enter is pressed. First argument is input value.
	 */
	onSubmit?: (value: string) => void
}

export type TextInputState = SharedTextInputState & {
	/**
	 * Suggested auto completion.
	 */
	suggestion: string | undefined

	/**
	 * Move cursor to the left.
	 */
	moveCursorLeft: () => void

	/**
	 * Move cursor to the right.
	 */
	moveCursorRight: () => void

	/**
	 * Insert text.
	 */
	insert: (text: string) => void

	/**
	 * Delete character.
	 */
	delete: () => void

	/**
	 * Submit input value.
	 */
	submit: () => void
}
//#endregion Hook Types

//#region Hook
export const useTextInputState = ({
	defaultValue = '',
	suggestions,
	onChange,
	onSubmit,
}: UseTextInputStateProps): TextInputState => {
	const [state, dispatch] = useReducer(
		textInputReducer,
		defaultValue,
		createInitialTextInputState
	)

	const suggestion = useMemo(
		() => findSuggestion(state.value, suggestions),
		[state.value, suggestions]
	)

	const moveCursorLeft = useCallback(() => {
		dispatch({
			type: 'move-cursor-left',
		})
	}, [])

	const moveCursorRight = useCallback(() => {
		dispatch({
			type: 'move-cursor-right',
		})
	}, [])

	const insert = useCallback((text: string) => {
		dispatch({
			type: 'insert',
			text,
		})
	}, [])

	const deleteCharacter = useCallback(() => {
		dispatch({
			type: 'delete',
		})
	}, [])

	const submit = useCallback(() => {
		if (suggestion) {
			insert(suggestion)
			onSubmit?.(state.value + suggestion)
			return
		}

		onSubmit?.(state.value)
	}, [state.value, suggestion, insert, onSubmit])

	useEffect(() => {
		if (state.value !== state.previousValue) {
			onChange?.(state.value)
		}
	}, [state.previousValue, state.value, onChange])

	return {
		...state,
		suggestion,
		moveCursorLeft,
		moveCursorRight,
		insert,
		delete: deleteCharacter,
		submit,
	}
}
//#endregion Hook

// packages/solid/src/composables/use-text-input-state.ts
import { createSignal, createMemo, createEffect, on } from 'solid-js'

//#region Types
export type UseTextInputStateProps = {
  defaultValue?: string
  suggestions?: string[]
  onChange?: (value: string) => void
  onSubmit?: (value: string) => void
}

export type TextInputState = {
  previousValue: () => string
  value: () => string
  cursorOffset: () => number
  suggestion: () => string | undefined
  moveCursorLeft: () => void
  moveCursorRight: () => void
  insert: (text: string) => void
  delete: () => void
  submit: () => void
}
//#endregion Types

//#region Composable
export const useTextInputState = ({
  defaultValue = '',
  suggestions,
  onChange,
  onSubmit,
}: UseTextInputStateProps = {}): TextInputState => {
  const [previousValue, setPreviousValue] = createSignal(defaultValue)
  const [value, setValue] = createSignal(defaultValue)
  const [cursorOffset, setCursorOffset] = createSignal(defaultValue.length)

  const suggestion = createMemo(() => {
    if (value().length === 0) return undefined
    return suggestions?.find((s) => s.startsWith(value()))?.replace(value(), '')
  })

  const moveCursorLeft = () => {
    setCursorOffset((o) => Math.max(0, o - 1))
  }

  const moveCursorRight = () => {
    setCursorOffset((o) => Math.min(value().length, o + 1))
  }

  const insert = (text: string) => {
    setPreviousValue(value())
    setValue((v) => v.slice(0, cursorOffset()) + text + v.slice(cursorOffset()))
    setCursorOffset((o) => o + text.length)
  }

  const deleteCharacter = () => {
    const newCursorOffset = Math.max(0, cursorOffset() - 1)
    setPreviousValue(value())
    setValue((v) => v.slice(0, newCursorOffset) + v.slice(newCursorOffset + 1))
    setCursorOffset(newCursorOffset)
  }

  const submit = () => {
    if (suggestion()) {
      insert(suggestion()!)
      onSubmit?.(value())
      return
    }
    onSubmit?.(value())
  }

  // WHY: defer:true skips initial run, matching Vue watch (change-only, not immediate)
  createEffect(on(value, (newVal) => { onChange?.(newVal) }, { defer: true }))

  return {
    previousValue,
    value,
    cursorOffset,
    suggestion,
    moveCursorLeft,
    moveCursorRight,
    insert,
    delete: deleteCharacter,
    submit,
  }
}
//#endregion Composable
