// packages/react/src/components/ui/use-spinner.ts
import {useEffect, useState} from 'react';
import spinners, {type SpinnerName} from 'cli-spinners';

//#region Types
export type UseSpinnerProps = {
	/**
	 * Type of a spinner.
	 * See [cli-spinners](https://github.com/sindresorhus/cli-spinners) for available spinners.
	 *
	 * @default dots
	 */
	type?: SpinnerName;
};

export type UseSpinnerResult = {
	frame: string;
};
//#endregion Types

//#region Hook
export function useSpinner({type = 'dots'}: UseSpinnerProps = {}): UseSpinnerResult {
	const [frame, setFrame] = useState(0);
	const spinner = spinners[type];

	useEffect(() => {
		const timer = setInterval(() => {
			setFrame(previousFrame => {
				const isLastFrame = previousFrame === spinner.frames.length - 1;
				return isLastFrame ? 0 : previousFrame + 1;
			});
		}, spinner.interval);

		return () => {
			clearInterval(timer);
		};
	}, [spinner]);

	return {
		frame: spinner.frames[frame] ?? '',
	};
}
//#endregion Hook

// packages/solid/src/composables/use-spinner.ts
import { createSignal, onCleanup } from 'solid-js'
import spinners, { type SpinnerName } from 'cli-spinners'

//#region Types
export type UseSpinnerProps = { type?: SpinnerName }
export type UseSpinnerResult = { frame: () => string }
//#endregion Types

export const useSpinner = ({ type = 'dots' }: UseSpinnerProps = {}): UseSpinnerResult => {
	const spinner = spinners[type]
	const [frameIndex, setFrameIndex] = createSignal(0)

	// WHY: direct setInterval (not onMount) — onMount doesn't fire in solid-js/universal
	const timer = setInterval(() => {
		setFrameIndex((i) => (i + 1) % spinner.frames.length)
	}, spinner.interval)

	onCleanup(() => clearInterval(timer))

	return { frame: () => spinner.frames[frameIndex()] ?? '' }
}
