// packages/react/src/components/PasswordInput/use-password-input.ts
import { useMemo } from 'react'
import chalk from 'chalk'
import { useInput } from '../../hooks/use-input'
import type { PasswordInputState } from './use-password-input-state'

//#region Types
export type UsePasswordInputProps = {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Password input state.
	 */
	state: PasswordInputState

	/**
	 * Text to display when `value` is empty.
	 *
	 * @default ""
	 */
	placeholder?: string
}

export type UsePasswordInputResult = {
	/**
	 * Value to render inside the input.
	 */
	inputValue: string
}
//#endregion Types

//#region Hook
const cursor = chalk.inverse(' ')

export const usePasswordInput = ({
	isDisabled = false,
	state,
	placeholder = '',
}: UsePasswordInputProps): UsePasswordInputResult => {
	const renderedPlaceholder = useMemo(() => {
		if (isDisabled) {
			return placeholder ? chalk.dim(placeholder) : ''
		}

		return placeholder && placeholder.length > 0
			? chalk.inverse(placeholder[0]!) + chalk.dim(placeholder.slice(1))
			: cursor
	}, [isDisabled, placeholder])

	const renderedValue = useMemo(() => {
		const value = '*'.repeat(state.value.length)

		if (isDisabled) {
			return value
		}

		let index = 0
		let result = value.length > 0 ? '' : cursor

		for (const char of value) {
			result += index === state.cursorOffset ? chalk.inverse(char) : char

			index++
		}

		if (value.length > 0 && state.cursorOffset === value.length) {
			result += cursor
		}

		return result
	}, [isDisabled, state.value, state.cursorOffset])

	useInput(
		(input, key) => {
			if (
				key.upArrow ||
				key.downArrow ||
				(key.ctrl && input === 'c') ||
				key.tab ||
				(key.shift && key.tab)
			) {
				return
			}

			if (key.return) {
				state.submit()
				return
			}

			if (key.leftArrow) {
				state.moveCursorLeft()
			} else if (key.rightArrow) {
				state.moveCursorRight()
			} else if (key.backspace || key.delete) {
				state.delete()
			} else {
				state.insert(input)
			}
		},
		{ isActive: !isDisabled }
	)

	return {
		inputValue: state.value.length > 0 ? renderedValue : renderedPlaceholder,
	}
}
//#endregion Hook

// packages/solid/src/composables/use-password-input.ts
import { createMemo } from 'solid-js'
import chalk from 'chalk'
import { useInput } from './use-input'
import type { PasswordInputState } from './use-password-input-state'

//#region Types
export type UsePasswordInputProps = {
  isDisabled?: () => boolean | undefined
  state: PasswordInputState
  placeholder?: string
}

export type UsePasswordInputResult = {
  inputValue: () => string
}
//#endregion Types

//#region Composable
const cursor = chalk.inverse(' ')

export const usePasswordInput = ({
  isDisabled,
  state,
  placeholder = '',
}: UsePasswordInputProps): UsePasswordInputResult => {
  const isActive = createMemo(() => !(isDisabled?.() ?? false))

  const renderedPlaceholder = createMemo(() => {
    if (isDisabled?.() ?? false) {
      return placeholder ? chalk.dim(placeholder) : ''
    }
    return placeholder && placeholder.length > 0
      ? chalk.inverse(placeholder[0]!) + chalk.dim(placeholder.slice(1))
      : cursor
  })

  const renderedValue = createMemo(() => {
    const maskedValue = '*'.repeat(state.value().length)

    if (isDisabled?.() ?? false) {
      return maskedValue
    }

    let index = 0
    let result = maskedValue.length > 0 ? '' : cursor

    for (const char of maskedValue) {
      result += index === state.cursorOffset() ? chalk.inverse(char) : char
      index++
    }

    if (maskedValue.length > 0 && state.cursorOffset() === maskedValue.length) {
      result += cursor
    }

    return result
  })

  useInput(
    (input, key) => {
      if (
        key.upArrow ||
        key.downArrow ||
        (key.ctrl && input === 'c') ||
        key.tab ||
        (key.shift && key.tab)
      ) {
        return
      }
      if (key.return) {
        state.submit()
        return
      }
      if (key.leftArrow) {
        state.moveCursorLeft()
      } else if (key.rightArrow) {
        state.moveCursorRight()
      } else if (key.backspace || key.delete) {
        state.delete()
      } else {
        state.insert(input)
      }
    },
    { isActive },
  )

  const inputValue = createMemo(() =>
    state.value().length > 0 ? renderedValue() : renderedPlaceholder(),
  )

  return { inputValue }
}
//#endregion Composable
