// packages/react/src/components/ui/ConfirmInput.tsx
import Text from '../Text'
import useInput from '../../hooks/use-input'
import { useComponentTheme } from '../../theme/theme'
import type { Props as TextProps } from '../Text'
import type { ComponentTheme } from '../../theme/theme'

//#region Theme
type ConfirmInputTheme = ComponentTheme & {
	styles: {
		input: (props: { isFocused: boolean }) => TextProps
	}
}

export const confirmInputTheme = {
	styles: {
		input: ({ isFocused }: { isFocused: boolean }): TextProps => ({
			style: {
				color: isFocused ? undefined : 'gray',
			},
		}),
	},
} satisfies ComponentTheme
//#endregion Theme

//#region Component
export type ConfirmInputProps = {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	readonly isDisabled?: boolean

	/**
	 * Default choice.
	 *
	 * @default "confirm"
	 */
	readonly defaultChoice?: 'confirm' | 'cancel'

	/**
	 * Confirm or cancel when user presses enter, depending on the `defaultChoice` value.
	 * Can be useful to disable when an explicit confirmation is required, such as pressing "Y" key.
	 *
	 * @default true
	 */
	readonly submitOnEnter?: boolean

	/**
	 * Callback to trigger on confirmation.
	 */
	readonly onConfirm: () => void

	/**
	 * Callback to trigger on cancellation.
	 */
	readonly onCancel: () => void
}

export function ConfirmInput({
	isDisabled = false,
	defaultChoice = 'confirm',
	submitOnEnter = true,
	onConfirm,
	onCancel,
}: ConfirmInputProps) {
	useInput(
		(input, key) => {
			if (input.toLowerCase() === 'y') {
				onConfirm()
			}

			if (input.toLowerCase() === 'n') {
				onCancel()
			}

			if (key.return && submitOnEnter) {
				if (defaultChoice === 'confirm') {
					onConfirm()
				} else {
					onCancel()
				}
			}
		},
		{ isActive: !isDisabled }
	)

	const { styles } = useComponentTheme<ConfirmInputTheme>('ConfirmInput')

	return (
		<Text {...styles.input({ isFocused: !isDisabled })}>
			{defaultChoice === 'confirm' ? 'Y/n' : 'y/N'}
		</Text>
	)
}
//#endregion Component

// packages/vue/src/components/ConfirmInput.tsx
import {
	defineComponent,
	computed,
	type PropType,
	type DefineComponent,
} from 'vue'
import { Text, type TextProps } from './Text'
import { useInput } from '../composables/use-input'
import { useComponentTheme, type IComponentTheme } from '../theme'

//#region Types
export interface ConfirmInputProps {
	/**
	 * When disabled, user input is ignored.
	 *
	 * @default false
	 */
	isDisabled?: boolean

	/**
	 * Default choice.
	 *
	 * @default "confirm"
	 */
	defaultChoice?: 'confirm' | 'cancel'

	/**
	 * Confirm or cancel when user presses enter, depending on the `defaultChoice` value.
	 * Can be useful to disable when an explicit confirmation is required, such as pressing "Y" key.
	 *
	 * @default true
	 */
	submitOnEnter?: boolean

	/**
	 * Callback to trigger on confirmation.
	 */
	onConfirm: () => void

	/**
	 * Callback to trigger on cancellation.
	 */
	onCancel: () => void
}

export type ConfirmInputTheme = IComponentTheme & {
	styles: {
		input: (props: { isFocused: boolean }) => Partial<TextProps>
	}
}
//#endregion Types

//#region Theme
export const confirmInputTheme: ConfirmInputTheme = {
	styles: {
		input: ({ isFocused }: { isFocused: boolean }): Partial<TextProps> => ({
			style: {
				color: isFocused ? undefined : 'gray',
			},
		}),
	},
}
//#endregion Theme

//#region Component
export const ConfirmInput: DefineComponent<ConfirmInputProps> = defineComponent(
	{
		name: 'ConfirmInput',
		props: {
			isDisabled: {
				type: Boolean,
				default: false,
			},
			defaultChoice: {
				type: String as PropType<'confirm' | 'cancel'>,
				default: 'confirm',
			},
			submitOnEnter: {
				type: Boolean,
				default: true,
			},
			onConfirm: {
				type: Function as PropType<() => void>,
				required: true,
			},
			onCancel: {
				type: Function as PropType<() => void>,
				required: true,
			},
		},
		setup(props) {
			const isActive = computed(() => !props.isDisabled)

			useInput(
				(input: string, key: { return?: boolean }) => {
					if (input.toLowerCase() === 'y') {
						props.onConfirm()
					}

					if (input.toLowerCase() === 'n') {
						props.onCancel()
					}

					if (key.return && props.submitOnEnter) {
						if (props.defaultChoice === 'confirm') {
							props.onConfirm()
						} else {
							props.onCancel()
						}
					}
				},
				{ isActive }
			)

			const theme = useComponentTheme<ConfirmInputTheme>('ConfirmInput')
			const { styles } = theme ?? confirmInputTheme

			return () => {
				return (
					<Text {...styles.input({ isFocused: !props.isDisabled })}>
						{props.defaultChoice === 'confirm' ? 'Y/n' : 'y/N'}
					</Text>
				)
			}
		},
	}
)
//#endregion Component

export type { ConfirmInputProps as Props, ConfirmInputProps as IProps }
