// examples/svelte_vite/src/screens/ListDemo.svelte
<script>
	import { Box, Text, OrderedList, OrderedListItem, UnorderedList, UnorderedListItem } from '@wolf-tui/svelte'
</script>

<Box className="flex-col gap-1 w-full">
	<!-- Ordered List -->
	<Text className="font-bold text-[#ffffff]">Ordered List</Text>
	<OrderedList>
		<OrderedListItem><Text>Install dependencies with pnpm</Text></OrderedListItem>
		<OrderedListItem><Text>Configure your environment</Text></OrderedListItem>
		<OrderedListItem><Text>Run the development server</Text></OrderedListItem>
		<OrderedListItem><Text>Build for production</Text></OrderedListItem>
	</OrderedList>

	<!-- Unordered List -->
	<Text className="font-bold mt-1 text-[#ffffff]">Unordered List</Text>
	<UnorderedList>
		<UnorderedListItem><Text>Supports Svelte 5 runes</Text></UnorderedListItem>
		<UnorderedListItem><Text>Full TypeScript support</Text></UnorderedListItem>
		<UnorderedListItem><Text>CSS preprocessing (SCSS, LESS, Stylus)</Text></UnorderedListItem>
		<UnorderedListItem><Text>Tailwind CSS integration</Text></UnorderedListItem>
	</UnorderedList>

	<!-- Nested Lists -->
	<Text className="font-bold mt-1 text-[#ffffff]">Nested Lists</Text>
	<OrderedList>
		<OrderedListItem><Text>Frontend</Text></OrderedListItem>
		<UnorderedList>
			<UnorderedListItem><Text>Svelte components</Text></UnorderedListItem>
			<UnorderedListItem><Text>Composables</Text></UnorderedListItem>
		</UnorderedList>
		<OrderedListItem><Text>Backend</Text></OrderedListItem>
		<UnorderedList>
			<UnorderedListItem><Text>API routes</Text></UnorderedListItem>
			<UnorderedListItem><Text>Database models</Text></UnorderedListItem>
		</UnorderedList>
	</OrderedList>
</Box>

// examples/vue_webpack/src/screens/ListDemo.vue
<template>
	<Box class="flex-col gap-1 w-full">
		<!-- Ordered List -->
		<Text class="font-bold text-white">Ordered List</Text>
		<OrderedList>
			<Text>Install dependencies with pnpm</Text>
			<Text>Configure your environment</Text>
			<Text>Run the development server</Text>
			<Text>Build for production</Text>
		</OrderedList>

		<!-- Unordered List -->
		<Text class="font-bold text-white mt-1">Unordered List</Text>
		<UnorderedList>
			<Text>Supports Vue 3 Composition API</Text>
			<Text>Full TypeScript support</Text>
			<Text>CSS preprocessing (SCSS, LESS, Stylus)</Text>
			<Text>Tailwind CSS integration</Text>
		</UnorderedList>

		<!-- Nested Lists -->
		<Text class="font-bold text-white mt-1">Nested Lists</Text>
		<OrderedList>
			<Text>Frontend</Text>
			<UnorderedList>
				<Text>Vue components</Text>
				<Text>Composables</Text>
			</UnorderedList>
			<Text>Backend</Text>
			<UnorderedList>
				<Text>API routes</Text>
				<Text>Database models</Text>
			</UnorderedList>
		</OrderedList>
	</Box>
</template>

<script setup lang="ts">
import { Box, Text, OrderedList, UnorderedList } from '@wolf-tui/vue'
</script>
