// examples/angular/esbuild/src/screens/style-demo.component.ts
import { Component } from '@angular/core'
import { BoxComponent, TextComponent } from '@wolfie/angular'

// Import CSS Modules
import buttonStyles from '../styles/Button.module.css'
import cardStyles from '../styles/Card.module.css'

@Component({
	selector: 'app-style-demo',
	standalone: true,
	imports: [BoxComponent, TextComponent],
	template: `
		<w-box class="flex-col w-full">
			<!-- Tailwind Section -->
			<w-box class="border-double border-yellow p-1 mb-1 flex-col w-full">
				<w-text class="text-[cyan]">
					Tailwind: border-double + arbitrary text-[cyan]
				</w-text>
			</w-box>

			<!-- SCSS Section -->
			<w-box class="card flex-col mb-1 w-full">
				<w-text class="card-title">SCSS Flavor</w-text>
				<w-text class="text-muted"
					>Nested selectors from components.scss</w-text
				>
			</w-box>

			<!-- LESS Section -->
			<w-box class="less-box flex-col mb-1 w-full">
				<w-text class="less-text">LESS Flavor</w-text>
				<w-text class="text-muted">Nesting from styles.less</w-text>
			</w-box>

			<!-- Stylus Section -->
			<w-box class="stylus-box flex-col mb-1 w-full">
				<w-text class="stylus-text">Stylus Flavor</w-text>
				<w-text class="text-muted">Indentation-based styles.styl</w-text>
			</w-box>

			<!-- CSS Modules Section -->
			<w-box [className]="[cardModuleClass, 'flex-col mb-1 w-full']">
				<w-text [className]="cardTitleClass">CSS Modules Flavor</w-text>
				<w-text class="text-muted">Scoped styles from Card.module.css</w-text>
			</w-box>

			<!-- Buttons Mix -->
			<w-box class="flex-row gap-2 w-full">
				<w-box class="btn primary">
					<w-text>SCSS Btn</w-text>
				</w-box>
				<w-box [className]="buttonClass">
					<w-text [className]="buttonTextClass">Module Btn</w-text>
				</w-box>
				<w-box class="bg-blue-600 p-x-2">
					<w-text class="text-white">Tailwind Btn</w-text>
				</w-box>
			</w-box>
		</w-box>
	`,
})
export class StyleDemoComponent {
	// CSS Module class names
	buttonClass = buttonStyles.button
	buttonTextClass = buttonStyles.text
	cardModuleClass = cardStyles.card
	cardTitleClass = cardStyles['card-title']
}

// examples/vue_webpack/src/screens/StyleDemo.vue
<template>
	<Box class="flex-col w-full">
		<!-- Tailwind Section -->
		<Box class="border-double border-yellow p-1 mb-1 flex-col w-full">
			<Text class="text-[cyan]">
				Tailwind: border-double + arbitrary text-[cyan]
			</Text>
		</Box>

		<!-- SCSS Section -->
		<Box class="card flex-col mb-1 w-full">
			<Text class="card-title">SCSS Flavor</Text>
			<Text class="text-muted"> Nested selectors from style lang="scss" </Text>
		</Box>

		<!-- LESS Section -->
		<Box class="less-box flex-col mb-1 w-full">
			<Text class="less-text">LESS Flavor</Text>
			<Text class="text-muted"> Nesting from style lang="less" </Text>
		</Box>

		<!-- Stylus Section -->
		<Box class="stylus-box flex-col mb-1 w-full">
			<Text class="stylus-text">Stylus Flavor</Text>
			<Text class="text-muted">Indentation-based style lang="stylus"</Text>
		</Box>

		<!-- CSS Modules Section -->
		<Box :class="[cardStyles.card, 'flex-col mb-1 w-full']">
			<Text :class="cardStyles.cardTitle">CSS Modules Flavor</Text>
			<Text class="text-muted">Scoped styles from Card.module.css</Text>
		</Box>

		<!-- SFC Module Style Section -->
		<Box :class="[$style.moduleBox, 'flex-col mb-1 w-full']">
			<Text :class="$style.moduleText">SFC Module Style</Text>
			<Text class="text-muted">Scoped via style module</Text>
		</Box>

		<!-- Buttons Mix -->
		<Box class="flex-row gap-2 w-full">
			<Box class="btn primary">
				<Text>SCSS Btn</Text>
			</Box>
			<Box :class="buttonStyles.button">
				<Text :class="buttonStyles.text">Module Btn</Text>
			</Box>
			<Box class="bg-blue-600 p-x-2">
				<Text class="text-white">Tailwind Btn</Text>
			</Box>
		</Box>
	</Box>
</template>

<script setup lang="ts">
import { Box, Text } from '@wolfie/vue'
import buttonStyles from '../styles/Button.module.css'
import cardStyles from '../styles/Card.module.css'

// Import global styles (side-effects)
import './StyleDemo.css'
import './StyleDemo.scss'
import './StyleDemo.less'
import './StyleDemo.styl'

// Import module styles and expose as $style for template
import styleDemoModule from './StyleDemo.module.css'
const $style = styleDemoModule
</script>
