// packages/create-wolf-tui/src/templates/starter/react/App.tsx
import React, { useState } from 'react'
import { Box, Text, useInput, useApp } from '@wolf-tui/react'

export default function App() {
	const [count, setCount] = useState(0)
	const { exit } = useApp()

	useInput((input, key) => {
		if (key.upArrow) setCount((c) => c + 1)
		if (key.downArrow) setCount((c) => c - 1)
		if (input === 'q') exit()
	})

	const color = count > 0 ? 'green' : count < 0 ? 'red' : 'white'

	return (
		<Box
			style={{
				flexDirection: 'column',
				borderStyle: 'round',
				borderColor: 'cyan',
				paddingLeft: 2,
				paddingRight: 2,
				paddingTop: 1,
				paddingBottom: 1,
				gap: 1,
				width: 40,
			}}
		>
			<Box style={{ justifyContent: 'center' }}>
				<Text style={{ fontWeight: 'bold', color: 'cyan' }}>wolf-tui</Text>
			</Box>

			<Box
				style={{
					justifyContent: 'center',
					borderStyle: 'single',
					borderColor: color,
					paddingLeft: 2,
					paddingRight: 2,
				}}
			>
				<Text style={{ fontWeight: 'bold', color }}>{count}</Text>
			</Box>

			<Box style={{ justifyContent: 'space-around' }}>
				<Text style={{ color: 'green' }}>↑ up</Text>
				<Text style={{ color: 'red' }}>↓ down</Text>
				<Text style={{ color: 'gray' }}>q quit</Text>
			</Box>
		</Box>
	)
}

// packages/create-wolf-tui/src/templates/starter/angular/app.component.ts
import { Component, signal, computed, inject } from '@angular/core'
import {
	BoxComponent,
	TextComponent,
	injectInput,
	AppService,
} from '@wolf-tui/angular'

@Component({
	selector: 'app-root',
	standalone: true,
	imports: [BoxComponent, TextComponent],
	template: `
		<w-box
			[style]="{
				flexDirection: 'column',
				borderStyle: 'round',
				borderColor: 'cyan',
				paddingLeft: 2,
				paddingRight: 2,
				paddingTop: 1,
				paddingBottom: 1,
				gap: 1,
				width: 40,
			}"
		>
			<w-box [style]="{ justifyContent: 'center' }">
				<w-text [style]="{ fontWeight: 'bold', color: 'cyan' }">
					wolf-tui
				</w-text>
			</w-box>

			<w-box
				[style]="{
					justifyContent: 'center',
					borderStyle: 'single',
					borderColor: color(),
					paddingLeft: 2,
					paddingRight: 2,
				}"
			>
				<w-text [style]="{ fontWeight: 'bold', color: color() }">
					{{ count() }}
				</w-text>
			</w-box>

			<w-box [style]="{ justifyContent: 'space-around' }">
				<w-text [style]="{ color: 'green' }">↑ up</w-text>
				<w-text [style]="{ color: 'red' }">↓ down</w-text>
				<w-text [style]="{ color: 'gray' }">q quit</w-text>
			</w-box>
		</w-box>
	`,
})
export class AppComponent {
	count = signal(0)
	color = computed(() =>
		this.count() > 0 ? 'green' : this.count() < 0 ? 'red' : 'white'
	)
	private app = inject(AppService)

	constructor() {
		injectInput((input, key) => {
			if (key.upArrow) this.count.update((c) => c + 1)
			if (key.downArrow) this.count.update((c) => c - 1)
			if (input === 'q') this.app.exit()
		})
	}
}
