// packages/solid/src/composables/use-text-input-state.ts
import { createSignal, createMemo, createEffect, on } from 'solid-js'

//#region Types
export type UseTextInputStateProps = {
  defaultValue?: string
  suggestions?: string[]
  onChange?: (value: string) => void
  onSubmit?: (value: string) => void
}

export type TextInputState = {
  previousValue: () => string
  value: () => string
  cursorOffset: () => number
  suggestion: () => string | undefined
  moveCursorLeft: () => void
  moveCursorRight: () => void
  insert: (text: string) => void
  delete: () => void
  submit: () => void
}
//#endregion Types

//#region Composable
export const useTextInputState = ({
  defaultValue = '',
  suggestions,
  onChange,
  onSubmit,
}: UseTextInputStateProps = {}): TextInputState => {
  const [previousValue, setPreviousValue] = createSignal(defaultValue)
  const [value, setValue] = createSignal(defaultValue)
  const [cursorOffset, setCursorOffset] = createSignal(defaultValue.length)

  const suggestion = createMemo(() => {
    if (value().length === 0) return undefined
    return suggestions?.find((s) => s.startsWith(value()))?.replace(value(), '')
  })

  const moveCursorLeft = () => {
    setCursorOffset((o) => Math.max(0, o - 1))
  }

  const moveCursorRight = () => {
    setCursorOffset((o) => Math.min(value().length, o + 1))
  }

  const insert = (text: string) => {
    setPreviousValue(value())
    setValue((v) => v.slice(0, cursorOffset()) + text + v.slice(cursorOffset()))
    setCursorOffset((o) => o + text.length)
  }

  const deleteCharacter = () => {
    const newCursorOffset = Math.max(0, cursorOffset() - 1)
    setPreviousValue(value())
    setValue((v) => v.slice(0, newCursorOffset) + v.slice(newCursorOffset + 1))
    setCursorOffset(newCursorOffset)
  }

  const submit = () => {
    if (suggestion()) {
      insert(suggestion()!)
      onSubmit?.(value())
      return
    }
    onSubmit?.(value())
  }

  // WHY: defer:true skips initial run, matching Vue watch (change-only, not immediate)
  createEffect(on(value, (newVal) => { onChange?.(newVal) }, { defer: true }))

  return {
    previousValue,
    value,
    cursorOffset,
    suggestion,
    moveCursorLeft,
    moveCursorRight,
    insert,
    delete: deleteCharacter,
    submit,
  }
}
//#endregion Composable

// packages/react/src/components/ui/TextInput/use-text-input-state.ts
import {
	useReducer,
	useCallback,
	useEffect,
	type Reducer,
	useMemo,
} from 'react'

//#region State Types
type State = {
	previousValue: string
	value: string
	cursorOffset: number
}

type Action =
	| MoveCursorLeftAction
	| MoveCursorRightAction
	| InsertAction
	| DeleteAction

type MoveCursorLeftAction = {
	type: 'move-cursor-left'
}

type MoveCursorRightAction = {
	type: 'move-cursor-right'
}

type InsertAction = {
	type: 'insert'
	text: string
}

type DeleteAction = {
	type: 'delete'
}
//#endregion State Types

//#region Reducer
const reducer: Reducer<State, Action> = (state, action) => {
	switch (action.type) {
		case 'move-cursor-left': {
			return {
				...state,
				cursorOffset: Math.max(0, state.cursorOffset - 1),
			}
		}

		case 'move-cursor-right': {
			return {
				...state,
				cursorOffset: Math.min(state.value.length, state.cursorOffset + 1),
			}
		}

		case 'insert': {
			return {
				...state,
				previousValue: state.value,
				value:
					state.value.slice(0, state.cursorOffset) +
					action.text +
					state.value.slice(state.cursorOffset),
				cursorOffset: state.cursorOffset + action.text.length,
			}
		}

		case 'delete': {
			const newCursorOffset = Math.max(0, state.cursorOffset - 1)

			return {
				...state,
				previousValue: state.value,
				value:
					state.value.slice(0, newCursorOffset) +
					state.value.slice(newCursorOffset + 1),
				cursorOffset: newCursorOffset,
			}
		}
	}
}
//#endregion Reducer

//#region Hook Types
export type UseTextInputStateProps = {
	/**
	 * Default input value.
	 */
	defaultValue?: string

	/**
	 * Suggestions to autocomplete the input value.
	 */
	suggestions?: string[]

	/**
	 * Callback when input value changes.
	 */
	onChange?: (value: string) => void

	/**
	 * Callback when enter is pressed. First argument is input value.
	 */
	onSubmit?: (value: string) => void
}

export type TextInputState = State & {
	/**
	 * Suggested auto completion.
	 */
	suggestion: string | undefined

	/**
	 * Move cursor to the left.
	 */
	moveCursorLeft: () => void

	/**
	 * Move cursor to the right.
	 */
	moveCursorRight: () => void

	/**
	 * Insert text.
	 */
	insert: (text: string) => void

	/**
	 * Delete character.
	 */
	delete: () => void

	/**
	 * Submit input value.
	 */
	submit: () => void
}
//#endregion Hook Types

//#region Hook
export const useTextInputState = ({
	defaultValue = '',
	suggestions,
	onChange,
	onSubmit,
}: UseTextInputStateProps): TextInputState => {
	const [state, dispatch] = useReducer(reducer, {
		previousValue: defaultValue,
		value: defaultValue,
		cursorOffset: defaultValue.length,
	})

	const suggestion = useMemo(() => {
		if (state.value.length === 0) {
			return
		}

		return suggestions
			?.find((suggestion) => suggestion.startsWith(state.value))
			?.replace(state.value, '')
	}, [state.value, suggestions])

	const moveCursorLeft = useCallback(() => {
		dispatch({
			type: 'move-cursor-left',
		})
	}, [])

	const moveCursorRight = useCallback(() => {
		dispatch({
			type: 'move-cursor-right',
		})
	}, [])

	const insert = useCallback((text: string) => {
		dispatch({
			type: 'insert',
			text,
		})
	}, [])

	const deleteCharacter = useCallback(() => {
		dispatch({
			type: 'delete',
		})
	}, [])

	const submit = useCallback(() => {
		if (suggestion) {
			insert(suggestion)
			onSubmit?.(state.value + suggestion)
			return
		}

		onSubmit?.(state.value)
	}, [state.value, suggestion, insert, onSubmit])

	useEffect(() => {
		if (state.value !== state.previousValue) {
			onChange?.(state.value)
		}
	}, [state.previousValue, state.value, onChange])

	return {
		...state,
		suggestion,
		moveCursorLeft,
		moveCursorRight,
		insert,
		delete: deleteCharacter,
		submit,
	}
}
//#endregion Hook
